// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/photo_share/proto/photo/photo.proto

package photo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-custom/graphql-gateway/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PhotoCategory int32

const (
	PhotoCategory_SELFIE    PhotoCategory = 0
	PhotoCategory_PORTRAIT  PhotoCategory = 1
	PhotoCategory_ACTION    PhotoCategory = 2
	PhotoCategory_LANDSCAPE PhotoCategory = 3
	PhotoCategory_GRAPHIC   PhotoCategory = 4
)

var PhotoCategory_name = map[int32]string{
	0: "SELFIE",
	1: "PORTRAIT",
	2: "ACTION",
	3: "LANDSCAPE",
	4: "GRAPHIC",
}

var PhotoCategory_value = map[string]int32{
	"SELFIE":    0,
	"PORTRAIT":  1,
	"ACTION":    2,
	"LANDSCAPE": 3,
	"GRAPHIC":   4,
}

func (x PhotoCategory) String() string {
	return proto.EnumName(PhotoCategory_name, int32(x))
}

func (PhotoCategory) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3dccad5f52c8e72e, []int{0}
}

type Photo struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string               `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category             PhotoCategory        `protobuf:"varint,5,opt,name=category,proto3,enum=photo.PhotoCategory" json:"category,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Photo) Reset()         { *m = Photo{} }
func (m *Photo) String() string { return proto.CompactTextString(m) }
func (*Photo) ProtoMessage()    {}
func (*Photo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dccad5f52c8e72e, []int{0}
}

func (m *Photo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Photo.Unmarshal(m, b)
}
func (m *Photo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Photo.Marshal(b, m, deterministic)
}
func (m *Photo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Photo.Merge(m, src)
}
func (m *Photo) XXX_Size() int {
	return xxx_messageInfo_Photo.Size(m)
}
func (m *Photo) XXX_DiscardUnknown() {
	xxx_messageInfo_Photo.DiscardUnknown(m)
}

var xxx_messageInfo_Photo proto.InternalMessageInfo

func (m *Photo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Photo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Photo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Photo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Photo) GetCategory() PhotoCategory {
	if m != nil {
		return m.Category
	}
	return PhotoCategory_SELFIE
}

func (m *Photo) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type TotalPhotosResponse struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalPhotosResponse) Reset()         { *m = TotalPhotosResponse{} }
func (m *TotalPhotosResponse) String() string { return proto.CompactTextString(m) }
func (*TotalPhotosResponse) ProtoMessage()    {}
func (*TotalPhotosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dccad5f52c8e72e, []int{1}
}

func (m *TotalPhotosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalPhotosResponse.Unmarshal(m, b)
}
func (m *TotalPhotosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalPhotosResponse.Marshal(b, m, deterministic)
}
func (m *TotalPhotosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalPhotosResponse.Merge(m, src)
}
func (m *TotalPhotosResponse) XXX_Size() int {
	return xxx_messageInfo_TotalPhotosResponse.Size(m)
}
func (m *TotalPhotosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalPhotosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TotalPhotosResponse proto.InternalMessageInfo

func (m *TotalPhotosResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AllPhotosResponse struct {
	Photos               []*Photo `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllPhotosResponse) Reset()         { *m = AllPhotosResponse{} }
func (m *AllPhotosResponse) String() string { return proto.CompactTextString(m) }
func (*AllPhotosResponse) ProtoMessage()    {}
func (*AllPhotosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dccad5f52c8e72e, []int{2}
}

func (m *AllPhotosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPhotosResponse.Unmarshal(m, b)
}
func (m *AllPhotosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPhotosResponse.Marshal(b, m, deterministic)
}
func (m *AllPhotosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPhotosResponse.Merge(m, src)
}
func (m *AllPhotosResponse) XXX_Size() int {
	return xxx_messageInfo_AllPhotosResponse.Size(m)
}
func (m *AllPhotosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPhotosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllPhotosResponse proto.InternalMessageInfo

func (m *AllPhotosResponse) GetPhotos() []*Photo {
	if m != nil {
		return m.Photos
	}
	return nil
}

type PhotoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhotoRequest) Reset()         { *m = PhotoRequest{} }
func (m *PhotoRequest) String() string { return proto.CompactTextString(m) }
func (*PhotoRequest) ProtoMessage()    {}
func (*PhotoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dccad5f52c8e72e, []int{3}
}

func (m *PhotoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoRequest.Unmarshal(m, b)
}
func (m *PhotoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoRequest.Marshal(b, m, deterministic)
}
func (m *PhotoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoRequest.Merge(m, src)
}
func (m *PhotoRequest) XXX_Size() int {
	return xxx_messageInfo_PhotoRequest.Size(m)
}
func (m *PhotoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoRequest proto.InternalMessageInfo

func (m *PhotoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PhotoResponse struct {
	Photo                *Photo   `protobuf:"bytes,1,opt,name=photo,proto3" json:"photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhotoResponse) Reset()         { *m = PhotoResponse{} }
func (m *PhotoResponse) String() string { return proto.CompactTextString(m) }
func (*PhotoResponse) ProtoMessage()    {}
func (*PhotoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dccad5f52c8e72e, []int{4}
}

func (m *PhotoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoResponse.Unmarshal(m, b)
}
func (m *PhotoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoResponse.Marshal(b, m, deterministic)
}
func (m *PhotoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoResponse.Merge(m, src)
}
func (m *PhotoResponse) XXX_Size() int {
	return xxx_messageInfo_PhotoResponse.Size(m)
}
func (m *PhotoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoResponse proto.InternalMessageInfo

func (m *PhotoResponse) GetPhoto() *Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

type PostPhotoRequest struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category             PhotoCategory `protobuf:"varint,2,opt,name=category,proto3,enum=photo.PhotoCategory" json:"category,omitempty"`
	Description          string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PostPhotoRequest) Reset()         { *m = PostPhotoRequest{} }
func (m *PostPhotoRequest) String() string { return proto.CompactTextString(m) }
func (*PostPhotoRequest) ProtoMessage()    {}
func (*PostPhotoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dccad5f52c8e72e, []int{5}
}

func (m *PostPhotoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostPhotoRequest.Unmarshal(m, b)
}
func (m *PostPhotoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostPhotoRequest.Marshal(b, m, deterministic)
}
func (m *PostPhotoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostPhotoRequest.Merge(m, src)
}
func (m *PostPhotoRequest) XXX_Size() int {
	return xxx_messageInfo_PostPhotoRequest.Size(m)
}
func (m *PostPhotoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostPhotoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostPhotoRequest proto.InternalMessageInfo

func (m *PostPhotoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PostPhotoRequest) GetCategory() PhotoCategory {
	if m != nil {
		return m.Category
	}
	return PhotoCategory_SELFIE
}

func (m *PostPhotoRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type TagPhotoRequest struct {
	GithubLogin          string   `protobuf:"bytes,1,opt,name=github_login,json=githubLogin,proto3" json:"github_login,omitempty"`
	PhotoId              string   `protobuf:"bytes,2,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagPhotoRequest) Reset()         { *m = TagPhotoRequest{} }
func (m *TagPhotoRequest) String() string { return proto.CompactTextString(m) }
func (*TagPhotoRequest) ProtoMessage()    {}
func (*TagPhotoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dccad5f52c8e72e, []int{6}
}

func (m *TagPhotoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagPhotoRequest.Unmarshal(m, b)
}
func (m *TagPhotoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagPhotoRequest.Marshal(b, m, deterministic)
}
func (m *TagPhotoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagPhotoRequest.Merge(m, src)
}
func (m *TagPhotoRequest) XXX_Size() int {
	return xxx_messageInfo_TagPhotoRequest.Size(m)
}
func (m *TagPhotoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagPhotoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TagPhotoRequest proto.InternalMessageInfo

func (m *TagPhotoRequest) GetGithubLogin() string {
	if m != nil {
		return m.GithubLogin
	}
	return ""
}

func (m *TagPhotoRequest) GetPhotoId() string {
	if m != nil {
		return m.PhotoId
	}
	return ""
}

func init() {
	proto.RegisterEnum("photo.PhotoCategory", PhotoCategory_name, PhotoCategory_value)
	proto.RegisterType((*Photo)(nil), "photo.Photo")
	proto.RegisterType((*TotalPhotosResponse)(nil), "photo.TotalPhotosResponse")
	proto.RegisterType((*AllPhotosResponse)(nil), "photo.AllPhotosResponse")
	proto.RegisterType((*PhotoRequest)(nil), "photo.PhotoRequest")
	proto.RegisterType((*PhotoResponse)(nil), "photo.PhotoResponse")
	proto.RegisterType((*PostPhotoRequest)(nil), "photo.PostPhotoRequest")
	proto.RegisterType((*TagPhotoRequest)(nil), "photo.TagPhotoRequest")
}

func init() {
	proto.RegisterFile("example/photo_share/proto/photo/photo.proto", fileDescriptor_3dccad5f52c8e72e)
}

var fileDescriptor_3dccad5f52c8e72e = []byte{
	// 617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xd1, 0x6e, 0xd3, 0x3c,
	0x18, 0xfd, 0x93, 0xae, 0x5d, 0xfa, 0xa5, 0xdb, 0x32, 0x6f, 0xff, 0x08, 0x41, 0x82, 0x12, 0x71,
	0x51, 0xad, 0x5a, 0x8b, 0xba, 0xdd, 0x20, 0x71, 0x53, 0x95, 0x02, 0x85, 0x69, 0x2b, 0x59, 0x2f,
	0xb8, 0x9b, 0xbc, 0xc4, 0xa4, 0x91, 0x92, 0x3a, 0x4b, 0x5c, 0xd8, 0x78, 0x14, 0x2e, 0xfb, 0x0e,
	0x7d, 0x06, 0x5e, 0x0b, 0xc5, 0x76, 0x4a, 0x9a, 0x32, 0xc4, 0x4d, 0x64, 0x9f, 0xf3, 0xf9, 0xd8,
	0xdf, 0x77, 0x4e, 0xa0, 0x4d, 0xee, 0x70, 0x14, 0x87, 0xa4, 0x1b, 0x4f, 0x29, 0xa3, 0xd7, 0xe9,
	0x14, 0x27, 0xa4, 0x1b, 0x27, 0x94, 0x51, 0x81, 0x88, 0x6f, 0x87, 0x23, 0xa8, 0xca, 0x37, 0xd6,
	0x99, 0x1f, 0xb0, 0xe9, 0xfc, 0xa6, 0xe3, 0xd2, 0xa8, 0xeb, 0x27, 0xb1, 0x7b, 0xe2, 0xce, 0x53,
	0xc6, 0xd7, 0x38, 0x9e, 0xde, 0x86, 0x27, 0x3e, 0x66, 0xe4, 0x1b, 0xbe, 0xcf, 0xf7, 0xe2, 0xb0,
	0xf5, 0xc4, 0xa7, 0xd4, 0x0f, 0xa5, 0xf8, 0xcd, 0xfc, 0x4b, 0x97, 0x44, 0x31, 0xbb, 0x97, 0xe4,
	0xb3, 0x32, 0xc9, 0x82, 0x88, 0xa4, 0x0c, 0x47, 0xb1, 0x28, 0xb0, 0x7f, 0x2a, 0x50, 0x1d, 0x67,
	0xb7, 0xa3, 0x5d, 0x50, 0x03, 0xcf, 0x54, 0x9a, 0x4a, 0xab, 0xee, 0xa8, 0x81, 0x87, 0x10, 0x6c,
	0xcd, 0x70, 0x44, 0x4c, 0x95, 0x23, 0x7c, 0x8d, 0x0c, 0xa8, 0xcc, 0x93, 0xd0, 0xac, 0x70, 0x28,
	0x5b, 0xa2, 0x26, 0xe8, 0x1e, 0x49, 0xdd, 0x24, 0x88, 0x59, 0x40, 0x67, 0xe6, 0x16, 0x67, 0x8a,
	0x10, 0x7a, 0x09, 0x9a, 0x8b, 0x19, 0xf1, 0x69, 0x72, 0x6f, 0x56, 0x9b, 0x4a, 0x6b, 0xb7, 0x77,
	0xd8, 0x11, 0xcd, 0xf3, 0x7b, 0x07, 0x92, 0x73, 0x56, 0x55, 0xe8, 0x0c, 0xb6, 0xdd, 0x84, 0x60,
	0x46, 0x3c, 0xb3, 0xd6, 0x54, 0x5a, 0x7a, 0xcf, 0xea, 0x88, 0x36, 0x3a, 0x79, 0x1b, 0x9d, 0x49,
	0xde, 0x86, 0x93, 0x97, 0xda, 0x6d, 0x38, 0x98, 0x50, 0x86, 0x43, 0xae, 0x9a, 0x3a, 0x24, 0x8d,
	0xe9, 0x2c, 0x25, 0xe8, 0x10, 0xaa, 0x2c, 0x83, 0x79, 0x67, 0x55, 0x47, 0x6c, 0xec, 0x57, 0xb0,
	0xdf, 0x0f, 0xcb, 0xa5, 0x2f, 0xa0, 0xc6, 0x1f, 0x96, 0x9a, 0x4a, 0xb3, 0xd2, 0xd2, 0x7b, 0x8d,
	0xe2, 0x3b, 0x1d, 0xc9, 0xd9, 0x4f, 0xa1, 0x21, 0x00, 0x72, 0x3b, 0x27, 0x29, 0x2b, 0xcf, 0xcd,
	0x3e, 0x85, 0x1d, 0xc9, 0x4b, 0x59, 0x1b, 0x84, 0xbf, 0xbc, 0xa6, 0xac, 0x2a, 0x28, 0xfb, 0x3b,
	0x18, 0x63, 0x9a, 0xb2, 0x35, 0xe1, 0xdc, 0x00, 0xa5, 0x60, 0x40, 0x71, 0x98, 0xea, 0x3f, 0x0d,
	0xb3, 0x64, 0x50, 0x65, 0xc3, 0x20, 0xfb, 0x12, 0xf6, 0x26, 0xd8, 0x5f, 0xbb, 0xfa, 0x39, 0x34,
	0x44, 0x16, 0xaf, 0x43, 0xea, 0x07, 0x33, 0xf9, 0x04, 0x5d, 0x60, 0xe7, 0x19, 0x84, 0x1e, 0x83,
	0x26, 0xa2, 0x1d, 0x78, 0x32, 0x22, 0xdb, 0x7c, 0x3f, 0xf2, 0x8e, 0x3f, 0xc9, 0x09, 0xe4, 0xaf,
	0x41, 0x00, 0xb5, 0xab, 0xe1, 0xf9, 0xdb, 0xd1, 0xd0, 0xf8, 0x0f, 0x35, 0x40, 0x1b, 0x5f, 0x3a,
	0x13, 0xa7, 0x3f, 0x9a, 0x18, 0x4a, 0xc6, 0xf4, 0x07, 0x93, 0xd1, 0xe5, 0x85, 0xa1, 0xa2, 0x1d,
	0xa8, 0x9f, 0xf7, 0x2f, 0xde, 0x5c, 0x0d, 0xfa, 0xe3, 0xa1, 0x51, 0x41, 0x3a, 0x6c, 0xbf, 0x73,
	0xfa, 0xe3, 0xf7, 0xa3, 0x81, 0xb1, 0xd5, 0xfb, 0x51, 0x91, 0x53, 0xbf, 0x22, 0xc9, 0xd7, 0xc0,
	0x25, 0xe8, 0x33, 0xe8, 0x05, 0xb7, 0xd1, 0xd1, 0x46, 0x42, 0x86, 0xd9, 0x5f, 0x60, 0x59, 0x72,
	0x3a, 0x7f, 0x48, 0x86, 0xfd, 0xff, 0x62, 0xd9, 0xde, 0x07, 0x9d, 0xfd, 0xa6, 0x8e, 0x55, 0xed,
	0x0e, 0x39, 0x50, 0x5f, 0x45, 0xe3, 0x41, 0x5d, 0x53, 0xea, 0x6e, 0x84, 0xc8, 0x3e, 0x58, 0x2c,
	0xdb, 0x7b, 0x50, 0xc7, 0x61, 0x51, 0x73, 0x90, 0xff, 0x64, 0x07, 0x6b, 0xe6, 0x8b, 0x69, 0x5b,
	0x87, 0xeb, 0xa0, 0x14, 0xda, 0x5b, 0x2c, 0xdb, 0xba, 0x8c, 0xce, 0xb1, 0xaa, 0xbd, 0x46, 0x1f,
	0xa1, 0xbe, 0xca, 0x08, 0x7a, 0x94, 0x9f, 0x29, 0xa5, 0xe6, 0x6f, 0x62, 0xa8, 0x1e, 0xaf, 0xce,
	0x7f, 0x00, 0x2d, 0x37, 0x1d, 0x1d, 0xe5, 0x43, 0x5a, 0x4f, 0x81, 0xf5, 0x40, 0xf3, 0xf6, 0xee,
	0x62, 0xd9, 0x06, 0xa4, 0x31, 0x59, 0x7e, 0x53, 0xe3, 0xfc, 0xe9, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc0, 0x0d, 0x36, 0xec, 0xf4, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PhotoServiceClient is the client API for PhotoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhotoServiceClient interface {
	TotalPhotos(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TotalPhotosResponse, error)
	AllPhotos(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AllPhotosResponse, error)
	Photo(ctx context.Context, in *PhotoRequest, opts ...grpc.CallOption) (*PhotoResponse, error)
	PostPhoto(ctx context.Context, in *PostPhotoRequest, opts ...grpc.CallOption) (*PhotoResponse, error)
	TagPhoto(ctx context.Context, in *TagPhotoRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type photoServiceClient struct {
	cc *grpc.ClientConn
}

func NewPhotoServiceClient(cc *grpc.ClientConn) PhotoServiceClient {
	return &photoServiceClient{cc}
}

func (c *photoServiceClient) TotalPhotos(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TotalPhotosResponse, error) {
	out := new(TotalPhotosResponse)
	err := c.cc.Invoke(ctx, "/photo.PhotoService/TotalPhotos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoServiceClient) AllPhotos(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AllPhotosResponse, error) {
	out := new(AllPhotosResponse)
	err := c.cc.Invoke(ctx, "/photo.PhotoService/AllPhotos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoServiceClient) Photo(ctx context.Context, in *PhotoRequest, opts ...grpc.CallOption) (*PhotoResponse, error) {
	out := new(PhotoResponse)
	err := c.cc.Invoke(ctx, "/photo.PhotoService/Photo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoServiceClient) PostPhoto(ctx context.Context, in *PostPhotoRequest, opts ...grpc.CallOption) (*PhotoResponse, error) {
	out := new(PhotoResponse)
	err := c.cc.Invoke(ctx, "/photo.PhotoService/PostPhoto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoServiceClient) TagPhoto(ctx context.Context, in *TagPhotoRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/photo.PhotoService/TagPhoto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhotoServiceServer is the server API for PhotoService service.
type PhotoServiceServer interface {
	TotalPhotos(context.Context, *empty.Empty) (*TotalPhotosResponse, error)
	AllPhotos(context.Context, *empty.Empty) (*AllPhotosResponse, error)
	Photo(context.Context, *PhotoRequest) (*PhotoResponse, error)
	PostPhoto(context.Context, *PostPhotoRequest) (*PhotoResponse, error)
	TagPhoto(context.Context, *TagPhotoRequest) (*empty.Empty, error)
}

func RegisterPhotoServiceServer(s *grpc.Server, srv PhotoServiceServer) {
	s.RegisterService(&_PhotoService_serviceDesc, srv)
}

func _PhotoService_TotalPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoServiceServer).TotalPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/photo.PhotoService/TotalPhotos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoServiceServer).TotalPhotos(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoService_AllPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoServiceServer).AllPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/photo.PhotoService/AllPhotos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoServiceServer).AllPhotos(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoService_Photo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoServiceServer).Photo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/photo.PhotoService/Photo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoServiceServer).Photo(ctx, req.(*PhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoService_PostPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoServiceServer).PostPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/photo.PhotoService/PostPhoto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoServiceServer).PostPhoto(ctx, req.(*PostPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoService_TagPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoServiceServer).TagPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/photo.PhotoService/TagPhoto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoServiceServer).TagPhoto(ctx, req.(*TagPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhotoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "photo.PhotoService",
	HandlerType: (*PhotoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TotalPhotos",
			Handler:    _PhotoService_TotalPhotos_Handler,
		},
		{
			MethodName: "AllPhotos",
			Handler:    _PhotoService_AllPhotos_Handler,
		},
		{
			MethodName: "Photo",
			Handler:    _PhotoService_Photo_Handler,
		},
		{
			MethodName: "PostPhoto",
			Handler:    _PhotoService_PostPhoto_Handler,
		},
		{
			MethodName: "TagPhoto",
			Handler:    _PhotoService_TagPhoto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/photo_share/proto/photo/photo.proto",
}
