// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/mixin/proto/review/review.proto

package review

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-custom/graphql-gateway/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Review struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	AuthorId             string   `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	ProductUpc           string   `protobuf:"bytes,4,opt,name=product_upc,json=productUpc,proto3" json:"product_upc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0b1fdf60f8846, []int{0}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Review) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Review) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Review) GetProductUpc() string {
	if m != nil {
		return m.ProductUpc
	}
	return ""
}

type GetReviewRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReviewRequest) Reset()         { *m = GetReviewRequest{} }
func (m *GetReviewRequest) String() string { return proto.CompactTextString(m) }
func (*GetReviewRequest) ProtoMessage()    {}
func (*GetReviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0b1fdf60f8846, []int{1}
}

func (m *GetReviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReviewRequest.Unmarshal(m, b)
}
func (m *GetReviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReviewRequest.Marshal(b, m, deterministic)
}
func (m *GetReviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReviewRequest.Merge(m, src)
}
func (m *GetReviewRequest) XXX_Size() int {
	return xxx_messageInfo_GetReviewRequest.Size(m)
}
func (m *GetReviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReviewRequest proto.InternalMessageInfo

func (m *GetReviewRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetReviewResponse struct {
	Review               *Review  `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReviewResponse) Reset()         { *m = GetReviewResponse{} }
func (m *GetReviewResponse) String() string { return proto.CompactTextString(m) }
func (*GetReviewResponse) ProtoMessage()    {}
func (*GetReviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0b1fdf60f8846, []int{2}
}

func (m *GetReviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReviewResponse.Unmarshal(m, b)
}
func (m *GetReviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReviewResponse.Marshal(b, m, deterministic)
}
func (m *GetReviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReviewResponse.Merge(m, src)
}
func (m *GetReviewResponse) XXX_Size() int {
	return xxx_messageInfo_GetReviewResponse.Size(m)
}
func (m *GetReviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReviewResponse proto.InternalMessageInfo

func (m *GetReviewResponse) GetReview() *Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type ListUserReviewsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	First                int32    `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserReviewsRequest) Reset()         { *m = ListUserReviewsRequest{} }
func (m *ListUserReviewsRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserReviewsRequest) ProtoMessage()    {}
func (*ListUserReviewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0b1fdf60f8846, []int{3}
}

func (m *ListUserReviewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserReviewsRequest.Unmarshal(m, b)
}
func (m *ListUserReviewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserReviewsRequest.Marshal(b, m, deterministic)
}
func (m *ListUserReviewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserReviewsRequest.Merge(m, src)
}
func (m *ListUserReviewsRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserReviewsRequest.Size(m)
}
func (m *ListUserReviewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserReviewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserReviewsRequest proto.InternalMessageInfo

func (m *ListUserReviewsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListUserReviewsRequest) GetFirst() int32 {
	if m != nil {
		return m.First
	}
	return 0
}

type ListUserReviewsResponse struct {
	Reviews              []*Review `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListUserReviewsResponse) Reset()         { *m = ListUserReviewsResponse{} }
func (m *ListUserReviewsResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserReviewsResponse) ProtoMessage()    {}
func (*ListUserReviewsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0b1fdf60f8846, []int{4}
}

func (m *ListUserReviewsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserReviewsResponse.Unmarshal(m, b)
}
func (m *ListUserReviewsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserReviewsResponse.Marshal(b, m, deterministic)
}
func (m *ListUserReviewsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserReviewsResponse.Merge(m, src)
}
func (m *ListUserReviewsResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserReviewsResponse.Size(m)
}
func (m *ListUserReviewsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserReviewsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserReviewsResponse proto.InternalMessageInfo

func (m *ListUserReviewsResponse) GetReviews() []*Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

type ListProductReviewsRequest struct {
	Upc                  string   `protobuf:"bytes,1,opt,name=upc,proto3" json:"upc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductReviewsRequest) Reset()         { *m = ListProductReviewsRequest{} }
func (m *ListProductReviewsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProductReviewsRequest) ProtoMessage()    {}
func (*ListProductReviewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0b1fdf60f8846, []int{5}
}

func (m *ListProductReviewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductReviewsRequest.Unmarshal(m, b)
}
func (m *ListProductReviewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductReviewsRequest.Marshal(b, m, deterministic)
}
func (m *ListProductReviewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductReviewsRequest.Merge(m, src)
}
func (m *ListProductReviewsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProductReviewsRequest.Size(m)
}
func (m *ListProductReviewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductReviewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductReviewsRequest proto.InternalMessageInfo

func (m *ListProductReviewsRequest) GetUpc() string {
	if m != nil {
		return m.Upc
	}
	return ""
}

type ListProductReviewsResponse struct {
	Reviews              []*Review `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListProductReviewsResponse) Reset()         { *m = ListProductReviewsResponse{} }
func (m *ListProductReviewsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProductReviewsResponse) ProtoMessage()    {}
func (*ListProductReviewsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0b1fdf60f8846, []int{6}
}

func (m *ListProductReviewsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductReviewsResponse.Unmarshal(m, b)
}
func (m *ListProductReviewsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductReviewsResponse.Marshal(b, m, deterministic)
}
func (m *ListProductReviewsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductReviewsResponse.Merge(m, src)
}
func (m *ListProductReviewsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProductReviewsResponse.Size(m)
}
func (m *ListProductReviewsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductReviewsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductReviewsResponse proto.InternalMessageInfo

func (m *ListProductReviewsResponse) GetReviews() []*Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func init() {
	proto.RegisterType((*Review)(nil), "review.Review")
	proto.RegisterType((*GetReviewRequest)(nil), "review.GetReviewRequest")
	proto.RegisterType((*GetReviewResponse)(nil), "review.GetReviewResponse")
	proto.RegisterType((*ListUserReviewsRequest)(nil), "review.ListUserReviewsRequest")
	proto.RegisterType((*ListUserReviewsResponse)(nil), "review.ListUserReviewsResponse")
	proto.RegisterType((*ListProductReviewsRequest)(nil), "review.ListProductReviewsRequest")
	proto.RegisterType((*ListProductReviewsResponse)(nil), "review.ListProductReviewsResponse")
}

func init() {
	proto.RegisterFile("example/mixin/proto/review/review.proto", fileDescriptor_d0f0b1fdf60f8846)
}

var fileDescriptor_d0f0b1fdf60f8846 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xd5, 0x6e, 0x3e, 0xda, 0x4c, 0x4b, 0x08, 0x73, 0x80, 0xed, 0x0a, 0x41, 0xf0, 0x85, 0x48,
	0xab, 0x24, 0x52, 0xcb, 0x89, 0x63, 0x2b, 0x15, 0x21, 0x71, 0x40, 0x46, 0x3d, 0x57, 0x1b, 0xaf,
	0x49, 0x2c, 0x35, 0xb5, 0x6b, 0x7b, 0xfb, 0xf1, 0x5f, 0x38, 0xf5, 0x98, 0xfb, 0x4a, 0xfc, 0x3c,
	0xb4, 0xb6, 0x17, 0x85, 0x24, 0x45, 0xea, 0x29, 0xf3, 0xf1, 0x66, 0xde, 0xcb, 0x1b, 0x2f, 0x7c,
	0xe4, 0xf7, 0xf9, 0x52, 0x5d, 0xf1, 0xe9, 0x52, 0xdc, 0x8b, 0xeb, 0xa9, 0xd2, 0xd2, 0xca, 0xa9,
	0xe6, 0xb7, 0x82, 0xdf, 0x85, 0x9f, 0x89, 0xab, 0x61, 0xd7, 0x67, 0xe9, 0xa7, 0xb9, 0xb0, 0x8b,
	0x72, 0x36, 0x61, 0x72, 0x39, 0x9d, 0x6b, 0xc5, 0xc6, 0xac, 0x34, 0xd6, 0xc5, 0xb9, 0x5a, 0xdc,
	0x5c, 0x8d, 0xe7, 0xb9, 0xe5, 0x77, 0xf9, 0x43, 0x93, 0xfb, 0x69, 0xf2, 0x2b, 0x82, 0x2e, 0x75,
	0x0b, 0xb0, 0x0f, 0xb1, 0x28, 0x92, 0x68, 0x18, 0x8d, 0x7a, 0x34, 0x16, 0x05, 0x22, 0xb4, 0x67,
	0xb2, 0x78, 0x48, 0x62, 0x57, 0x71, 0x31, 0x66, 0xd0, 0xcb, 0x4b, 0xbb, 0x90, 0xfa, 0x52, 0x14,
	0x49, 0xab, 0x6e, 0x9c, 0xf6, 0x57, 0x55, 0x06, 0xd0, 0xbe, 0x30, 0x5c, 0x63, 0x2c, 0x0a, 0xba,
	0xef, 0x01, 0x5f, 0x0b, 0x3c, 0x81, 0x03, 0xa5, 0x65, 0x51, 0x32, 0x7b, 0x59, 0x2a, 0x96, 0xb4,
	0x1d, 0x1c, 0x57, 0x55, 0xd6, 0x87, 0xbd, 0xef, 0xbe, 0x81, 0xad, 0x52, 0x31, 0x0a, 0x01, 0x76,
	0xa1, 0xd8, 0xe7, 0xc3, 0xc7, 0x2a, 0xdb, 0x6f, 0x34, 0x11, 0x02, 0x83, 0x2f, 0xdc, 0xfa, 0x84,
	0xf2, 0x9b, 0x92, 0x1b, 0xbb, 0xa9, 0x93, 0x9c, 0xc1, 0xab, 0x35, 0x8c, 0x51, 0xf2, 0xda, 0x70,
	0x9c, 0x40, 0xf0, 0xc5, 0x01, 0x0f, 0x8e, 0xfb, 0x93, 0x60, 0x9a, 0xc7, 0x9d, 0x76, 0x1f, 0xab,
	0x2c, 0x1e, 0x45, 0x34, 0xa0, 0xc8, 0x39, 0xbc, 0xfe, 0x26, 0x8c, 0xad, 0xff, 0x85, 0x47, 0x98,
	0x27, 0xe8, 0xf0, 0x2d, 0x74, 0x7e, 0x0a, 0x6d, 0xac, 0xf3, 0xa5, 0xe3, 0x17, 0x0d, 0x3b, 0xd4,
	0x17, 0xc9, 0x19, 0xbc, 0xd9, 0xda, 0x13, 0x24, 0x8d, 0x60, 0xcf, 0x93, 0x99, 0x24, 0x1a, 0xb6,
	0xb6, 0x35, 0xd1, 0xa6, 0x4d, 0xc6, 0x70, 0x54, 0x2f, 0x09, 0x1e, 0x6d, 0xe8, 0x19, 0x40, 0xed,
	0x59, 0x10, 0x54, 0x87, 0xe4, 0x1c, 0xd2, 0x5d, 0xf0, 0xe7, 0xd2, 0x1e, 0xff, 0x8e, 0xe1, 0x85,
	0xaf, 0xfd, 0xe0, 0xfa, 0x56, 0x30, 0x8e, 0x14, 0x7a, 0x7f, 0xad, 0xc5, 0xa4, 0x99, 0xdb, 0xbc,
	0x48, 0x7a, 0xb4, 0xa3, 0xe3, 0xd9, 0xc9, 0x60, 0x55, 0x65, 0x87, 0x18, 0xce, 0x99, 0xd6, 0xfe,
	0xcd, 0xe0, 0xe5, 0x86, 0x43, 0xf8, 0xae, 0x99, 0xdf, 0x7d, 0x82, 0xf4, 0xfd, 0x93, 0xfd, 0xc0,
	0xb2, 0xf6, 0x06, 0x1d, 0x87, 0x04, 0xdc, 0x76, 0x04, 0x3f, 0xac, 0xaf, 0xd9, 0x69, 0x6e, 0x4a,
	0xfe, 0x07, 0x09, 0x64, 0xff, 0xbe, 0xe0, 0xb4, 0x3e, 0xc1, 0xac, 0xeb, 0xbe, 0xa6, 0x93, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x76, 0xcd, 0x88, 0x95, 0xb6, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReviewServiceClient is the client API for ReviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReviewServiceClient interface {
	GetReview(ctx context.Context, in *GetReviewRequest, opts ...grpc.CallOption) (*GetReviewResponse, error)
	ListUserReviews(ctx context.Context, in *ListUserReviewsRequest, opts ...grpc.CallOption) (*ListUserReviewsResponse, error)
	ListProductReviews(ctx context.Context, in *ListProductReviewsRequest, opts ...grpc.CallOption) (*ListProductReviewsResponse, error)
}

type reviewServiceClient struct {
	cc *grpc.ClientConn
}

func NewReviewServiceClient(cc *grpc.ClientConn) ReviewServiceClient {
	return &reviewServiceClient{cc}
}

func (c *reviewServiceClient) GetReview(ctx context.Context, in *GetReviewRequest, opts ...grpc.CallOption) (*GetReviewResponse, error) {
	out := new(GetReviewResponse)
	err := c.cc.Invoke(ctx, "/review.ReviewService/GetReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewServiceClient) ListUserReviews(ctx context.Context, in *ListUserReviewsRequest, opts ...grpc.CallOption) (*ListUserReviewsResponse, error) {
	out := new(ListUserReviewsResponse)
	err := c.cc.Invoke(ctx, "/review.ReviewService/ListUserReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewServiceClient) ListProductReviews(ctx context.Context, in *ListProductReviewsRequest, opts ...grpc.CallOption) (*ListProductReviewsResponse, error) {
	out := new(ListProductReviewsResponse)
	err := c.cc.Invoke(ctx, "/review.ReviewService/ListProductReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewServiceServer is the server API for ReviewService service.
type ReviewServiceServer interface {
	GetReview(context.Context, *GetReviewRequest) (*GetReviewResponse, error)
	ListUserReviews(context.Context, *ListUserReviewsRequest) (*ListUserReviewsResponse, error)
	ListProductReviews(context.Context, *ListProductReviewsRequest) (*ListProductReviewsResponse, error)
}

func RegisterReviewServiceServer(s *grpc.Server, srv ReviewServiceServer) {
	s.RegisterService(&_ReviewService_serviceDesc, srv)
}

func _ReviewService_GetReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).GetReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.ReviewService/GetReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).GetReview(ctx, req.(*GetReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewService_ListUserReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).ListUserReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.ReviewService/ListUserReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).ListUserReviews(ctx, req.(*ListUserReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewService_ListProductReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).ListProductReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.ReviewService/ListProductReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).ListProductReviews(ctx, req.(*ListProductReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReviewService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "review.ReviewService",
	HandlerType: (*ReviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReview",
			Handler:    _ReviewService_GetReview_Handler,
		},
		{
			MethodName: "ListUserReviews",
			Handler:    _ReviewService_ListUserReviews_Handler,
		},
		{
			MethodName: "ListProductReviews",
			Handler:    _ReviewService_ListProductReviews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/mixin/proto/review/review.proto",
}
