// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/federation/proto/account/account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-custom/graphql-gateway/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_7614c5386d5f4a2a, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetMeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMeRequest) Reset()         { *m = GetMeRequest{} }
func (m *GetMeRequest) String() string { return proto.CompactTextString(m) }
func (*GetMeRequest) ProtoMessage()    {}
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7614c5386d5f4a2a, []int{1}
}

func (m *GetMeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMeRequest.Unmarshal(m, b)
}
func (m *GetMeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMeRequest.Marshal(b, m, deterministic)
}
func (m *GetMeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMeRequest.Merge(m, src)
}
func (m *GetMeRequest) XXX_Size() int {
	return xxx_messageInfo_GetMeRequest.Size(m)
}
func (m *GetMeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMeRequest proto.InternalMessageInfo

type GetMeResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMeResponse) Reset()         { *m = GetMeResponse{} }
func (m *GetMeResponse) String() string { return proto.CompactTextString(m) }
func (*GetMeResponse) ProtoMessage()    {}
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7614c5386d5f4a2a, []int{2}
}

func (m *GetMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMeResponse.Unmarshal(m, b)
}
func (m *GetMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMeResponse.Marshal(b, m, deterministic)
}
func (m *GetMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMeResponse.Merge(m, src)
}
func (m *GetMeResponse) XXX_Size() int {
	return xxx_messageInfo_GetMeResponse.Size(m)
}
func (m *GetMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMeResponse proto.InternalMessageInfo

func (m *GetMeResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type MultiGetUsersRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiGetUsersRequest) Reset()         { *m = MultiGetUsersRequest{} }
func (m *MultiGetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*MultiGetUsersRequest) ProtoMessage()    {}
func (*MultiGetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7614c5386d5f4a2a, []int{3}
}

func (m *MultiGetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiGetUsersRequest.Unmarshal(m, b)
}
func (m *MultiGetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiGetUsersRequest.Marshal(b, m, deterministic)
}
func (m *MultiGetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiGetUsersRequest.Merge(m, src)
}
func (m *MultiGetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_MultiGetUsersRequest.Size(m)
}
func (m *MultiGetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiGetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiGetUsersRequest proto.InternalMessageInfo

func (m *MultiGetUsersRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type MultiGetUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiGetUsersResponse) Reset()         { *m = MultiGetUsersResponse{} }
func (m *MultiGetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*MultiGetUsersResponse) ProtoMessage()    {}
func (*MultiGetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7614c5386d5f4a2a, []int{4}
}

func (m *MultiGetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiGetUsersResponse.Unmarshal(m, b)
}
func (m *MultiGetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiGetUsersResponse.Marshal(b, m, deterministic)
}
func (m *MultiGetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiGetUsersResponse.Merge(m, src)
}
func (m *MultiGetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_MultiGetUsersResponse.Size(m)
}
func (m *MultiGetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiGetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultiGetUsersResponse proto.InternalMessageInfo

func (m *MultiGetUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7614c5386d5f4a2a, []int{5}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7614c5386d5f4a2a, []int{6}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "account.User")
	proto.RegisterType((*GetMeRequest)(nil), "account.GetMeRequest")
	proto.RegisterType((*GetMeResponse)(nil), "account.GetMeResponse")
	proto.RegisterType((*MultiGetUsersRequest)(nil), "account.MultiGetUsersRequest")
	proto.RegisterType((*MultiGetUsersResponse)(nil), "account.MultiGetUsersResponse")
	proto.RegisterType((*GetUserRequest)(nil), "account.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "account.GetUserResponse")
}

func init() {
	proto.RegisterFile("example/federation/proto/account/account.proto", fileDescriptor_7614c5386d5f4a2a)
}

var fileDescriptor_7614c5386d5f4a2a = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x14, 0xc4, 0x8e, 0xeb, 0x36, 0xaf, 0xc4, 0x45, 0xab, 0x16, 0x2c, 0x4b, 0x40, 0x59, 0x2e, 0x45,
	0x56, 0x6d, 0x28, 0x5c, 0xa8, 0x7a, 0x80, 0x5c, 0x2a, 0x21, 0x55, 0x42, 0x46, 0x70, 0x45, 0x1b,
	0xfb, 0x91, 0xac, 0x14, 0x7f, 0xc4, 0xbb, 0x4e, 0xe0, 0xef, 0xf8, 0x3f, 0xf8, 0xbf, 0x71, 0x44,
	0x5e, 0xaf, 0x4d, 0x48, 0xe0, 0xc0, 0xc9, 0xef, 0xcd, 0x78, 0x66, 0xf4, 0x46, 0x0b, 0x01, 0x7e,
	0x67, 0x69, 0xb1, 0xc4, 0xf0, 0x1b, 0x26, 0x58, 0x32, 0xc9, 0xf3, 0x2c, 0x2c, 0xca, 0x5c, 0xe6,
	0x21, 0x8b, 0xe3, 0xbc, 0xca, 0x64, 0xff, 0x0d, 0x14, 0x4a, 0x0e, 0xf5, 0xea, 0xbd, 0x99, 0x73,
	0xb9, 0xa8, 0x66, 0x41, 0x9c, 0xa7, 0xe1, 0xbc, 0x2c, 0xe2, 0xcb, 0xb8, 0x12, 0x52, 0xcd, 0xac,
	0x58, 0xac, 0x96, 0x97, 0x73, 0x26, 0x71, 0xc3, 0x7e, 0xf4, 0x7b, 0x27, 0xa7, 0x5f, 0xc0, 0xfa,
	0x2c, 0xb0, 0x24, 0x0e, 0x98, 0x3c, 0x71, 0x8d, 0x73, 0xe3, 0x62, 0x1c, 0x99, 0x3c, 0x21, 0x04,
	0xac, 0x8c, 0xa5, 0xe8, 0x9a, 0x0a, 0x51, 0x33, 0xf1, 0xe0, 0xa8, 0x12, 0x58, 0x2a, 0x7c, 0xa4,
	0xf0, 0x61, 0xbf, 0x76, 0xea, 0xc6, 0x07, 0xed, 0x65, 0xf2, 0x84, 0x3a, 0x70, 0xff, 0x16, 0xe5,
	0x1d, 0x46, 0xb8, 0xaa, 0x50, 0x48, 0x7a, 0x0d, 0x13, 0xbd, 0x8b, 0x22, 0xcf, 0x04, 0x92, 0x17,
	0x60, 0xb5, 0x62, 0x15, 0x79, 0x7c, 0x35, 0x09, 0xfa, 0xab, 0x5a, 0x87, 0xa9, 0x5d, 0x37, 0xbe,
	0xf9, 0xd2, 0x88, 0xd4, 0x2f, 0xf4, 0x2d, 0x9c, 0xde, 0x55, 0x4b, 0xc9, 0x6f, 0x51, 0xb6, 0xac,
	0xd0, 0x9e, 0xe4, 0x19, 0x8c, 0x78, 0x22, 0x5c, 0xe3, 0x7c, 0x74, 0x31, 0x9e, 0x9e, 0xd4, 0x8d,
	0x7f, 0xfc, 0x61, 0xcc, 0x2a, 0xb9, 0xc8, 0xcb, 0xaf, 0x3c, 0x89, 0x5a, 0x8e, 0xde, 0xc0, 0xd9,
	0x8e, 0x54, 0xc7, 0x3f, 0x87, 0x83, 0xd6, 0xbb, 0x53, 0xef, 0xe6, 0x47, 0x1d, 0x47, 0x5f, 0x81,
	0xa3, 0x85, 0x7d, 0xe4, 0xd3, 0xdf, 0x35, 0xed, 0x27, 0xb6, 0x77, 0xdf, 0xc0, 0xc9, 0x20, 0xf9,
	0xef, 0x4b, 0xaf, 0x7e, 0x1a, 0xe0, 0xbc, 0xef, 0xe8, 0x4f, 0x58, 0xae, 0x79, 0x8c, 0xe4, 0x1d,
	0x1c, 0xa8, 0xe2, 0xc8, 0xd9, 0x20, 0xdc, 0x2e, 0xd6, 0x7b, 0xb8, 0x0b, 0x77, 0xa9, 0xf4, 0xa8,
	0x6e, 0x7c, 0x0b, 0xcc, 0x14, 0xc9, 0x47, 0x98, 0xfc, 0xd1, 0x01, 0x79, 0x3c, 0x48, 0xfe, 0x56,
	0xab, 0xf7, 0xe4, 0x5f, 0xb4, 0x76, 0xbe, 0x47, 0x22, 0x38, 0xd4, 0x28, 0x79, 0xb4, 0x1d, 0xbf,
	0xd5, 0x94, 0xe7, 0xee, 0x13, 0x5a, 0x7f, 0x5a, 0x37, 0xfe, 0x03, 0x6a, 0x47, 0xb8, 0xe6, 0xb8,
	0x99, 0xda, 0x5d, 0x7f, 0x33, 0x5b, 0xbd, 0xc7, 0xd7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfd,
	0x70, 0x4f, 0x68, 0x00, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error)
	MultiGetUsers(ctx context.Context, in *MultiGetUsersRequest, opts ...grpc.CallOption) (*MultiGetUsersResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error) {
	out := new(GetMeResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) MultiGetUsers(ctx context.Context, in *MultiGetUsersRequest, opts ...grpc.CallOption) (*MultiGetUsersResponse, error) {
	out := new(MultiGetUsersResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/MultiGetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error)
	MultiGetUsers(context.Context, *MultiGetUsersRequest) (*MultiGetUsersResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_MultiGetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiGetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).MultiGetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/MultiGetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).MultiGetUsers(ctx, req.(*MultiGetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMe",
			Handler:    _AccountService_GetMe_Handler,
		},
		{
			MethodName: "MultiGetUsers",
			Handler:    _AccountService_MultiGetUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AccountService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/federation/proto/account/account.proto",
}
