// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/mixin/proto/account/account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-custom/graphql-gateway/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc6f71cdff3da62, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetMeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMeRequest) Reset()         { *m = GetMeRequest{} }
func (m *GetMeRequest) String() string { return proto.CompactTextString(m) }
func (*GetMeRequest) ProtoMessage()    {}
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc6f71cdff3da62, []int{1}
}

func (m *GetMeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMeRequest.Unmarshal(m, b)
}
func (m *GetMeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMeRequest.Marshal(b, m, deterministic)
}
func (m *GetMeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMeRequest.Merge(m, src)
}
func (m *GetMeRequest) XXX_Size() int {
	return xxx_messageInfo_GetMeRequest.Size(m)
}
func (m *GetMeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMeRequest proto.InternalMessageInfo

type GetMeResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMeResponse) Reset()         { *m = GetMeResponse{} }
func (m *GetMeResponse) String() string { return proto.CompactTextString(m) }
func (*GetMeResponse) ProtoMessage()    {}
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc6f71cdff3da62, []int{2}
}

func (m *GetMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMeResponse.Unmarshal(m, b)
}
func (m *GetMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMeResponse.Marshal(b, m, deterministic)
}
func (m *GetMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMeResponse.Merge(m, src)
}
func (m *GetMeResponse) XXX_Size() int {
	return xxx_messageInfo_GetMeResponse.Size(m)
}
func (m *GetMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMeResponse proto.InternalMessageInfo

func (m *GetMeResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc6f71cdff3da62, []int{3}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc6f71cdff3da62, []int{4}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "account.User")
	proto.RegisterType((*GetMeRequest)(nil), "account.GetMeRequest")
	proto.RegisterType((*GetMeResponse)(nil), "account.GetMeResponse")
	proto.RegisterType((*GetUserRequest)(nil), "account.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "account.GetUserResponse")
}

func init() {
	proto.RegisterFile("example/mixin/proto/account/account.proto", fileDescriptor_dfc6f71cdff3da62)
}

var fileDescriptor_dfc6f71cdff3da62 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xbd, 0x4e, 0xf3, 0x40,
	0x10, 0x94, 0xef, 0xf3, 0x97, 0x84, 0x85, 0x18, 0xe9, 0x24, 0x20, 0x72, 0x15, 0x5d, 0x95, 0xc8,
	0x4a, 0x2c, 0x05, 0xaa, 0x88, 0x02, 0x68, 0xd2, 0x40, 0x63, 0xc4, 0x03, 0x5c, 0x2e, 0xab, 0xe4,
	0xa4, 0xf8, 0x27, 0xbe, 0x33, 0x84, 0xb7, 0x41, 0x2e, 0xe9, 0xfd, 0x7e, 0xc8, 0xe7, 0x1f, 0x59,
	0xa1, 0xa2, 0xf2, 0xce, 0xec, 0xce, 0xec, 0x8e, 0x0f, 0xa6, 0x78, 0xe4, 0x61, 0xb2, 0x47, 0x3f,
	0x94, 0x47, 0x19, 0xf9, 0x49, 0x1a, 0xeb, 0xd8, 0xe7, 0x42, 0xc4, 0x59, 0xa4, 0x9b, 0xef, 0xdc,
	0xb0, 0xb4, 0x5f, 0x43, 0xf7, 0x6e, 0x2b, 0xf5, 0x2e, 0x5b, 0xcf, 0x45, 0x1c, 0xfa, 0xdb, 0x34,
	0x11, 0x33, 0x91, 0x29, 0x6d, 0x6a, 0x9e, 0xec, 0x0e, 0xfb, 0xd9, 0x96, 0x6b, 0xfc, 0xe0, 0x9f,
	0x0d, 0xae, 0xe4, 0x2c, 0x00, 0xfb, 0x4d, 0x61, 0x4a, 0x1d, 0x20, 0x72, 0x33, 0xb2, 0xc6, 0xd6,
	0xe4, 0x2c, 0x20, 0x72, 0x43, 0x29, 0xd8, 0x11, 0x0f, 0x71, 0x44, 0x0c, 0x63, 0x6a, 0xea, 0xc2,
	0x20, 0x53, 0x98, 0x1a, 0xfe, 0x9f, 0xe1, 0x5b, 0xbc, 0x84, 0xbc, 0xf0, 0x7a, 0x95, 0x17, 0x73,
	0xe0, 0x62, 0x85, 0xfa, 0x05, 0x03, 0x3c, 0x64, 0xa8, 0x34, 0x5b, 0xc2, 0xb0, 0xc6, 0x2a, 0x89,
	0x23, 0x85, 0x74, 0x0a, 0x76, 0x29, 0x34, 0xeb, 0xce, 0x17, 0xc3, 0x79, 0x93, 0xa8, 0x54, 0x3f,
	0xf5, 0xf2, 0xc2, 0x23, 0x13, 0x2b, 0x30, 0x23, 0x6c, 0x0c, 0xce, 0x0a, 0x75, 0xd9, 0xa8, 0xdd,
	0x4e, 0x2f, 0x65, 0xf7, 0x70, 0xd9, 0x4e, 0xfc, 0xd9, 0x7f, 0xf1, 0x65, 0x81, 0xf3, 0x58, 0xb5,
	0x5f, 0x31, 0x7d, 0x97, 0x02, 0xe9, 0x03, 0xfc, 0x37, 0xe7, 0xd2, 0xab, 0x56, 0xd8, 0x8d, 0xe3,
	0x5e, 0x9f, 0xd2, 0xd5, 0x56, 0x36, 0xc8, 0x0b, 0xcf, 0x06, 0x12, 0x22, 0x7d, 0x86, 0x7e, 0x7d,
	0x12, 0xbd, 0xe9, 0x0e, 0x77, 0x62, 0xb8, 0xa3, 0xdf, 0x8d, 0xda, 0xc7, 0xf9, 0x2e, 0x3c, 0xa0,
	0xe6, 0x57, 0xba, 0x44, 0x6e, 0xd6, 0x3d, 0xf3, 0x52, 0xb7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x40, 0xf9, 0x4d, 0x06, 0x15, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error) {
	out := new(GetMeResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMe",
			Handler:    _AccountService_GetMe_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AccountService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/mixin/proto/account/account.proto",
}
