// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/red/red.proto

package red

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-custom/graphql-gateway/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Size int32

const (
	Size_SMALL  Size = 0
	Size_MIDDLE Size = 1
	Size_LARGE  Size = 2
)

var Size_name = map[int32]string{
	0: "SMALL",
	1: "MIDDLE",
	2: "LARGE",
}

var Size_value = map[string]int32{
	"SMALL":  0,
	"MIDDLE": 1,
	"LARGE":  2,
}

func (x Size) String() string {
	return proto.EnumName(Size_name, int32(x))
}

func (Size) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{0}
}

type ListRequest_Type int32

const (
	ListRequest_UNKNOWN ListRequest_Type = 0
	ListRequest_ENABLED ListRequest_Type = 1
)

var ListRequest_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "ENABLED",
}

var ListRequest_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"ENABLED": 1,
}

func (x ListRequest_Type) String() string {
	return proto.EnumName(ListRequest_Type_name, int32(x))
}

func (ListRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{3, 0}
}

type Red struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            int64    `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Enabled              bool     `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Point                float64  `protobuf:"fixed64,6,opt,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Red) Reset()         { *m = Red{} }
func (m *Red) String() string { return proto.CompactTextString(m) }
func (*Red) ProtoMessage()    {}
func (*Red) Descriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{0}
}

func (m *Red) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Red.Unmarshal(m, b)
}
func (m *Red) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Red.Marshal(b, m, deterministic)
}
func (m *Red) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Red.Merge(m, src)
}
func (m *Red) XXX_Size() int {
	return xxx_messageInfo_Red.Size(m)
}
func (m *Red) XXX_DiscardUnknown() {
	xxx_messageInfo_Red.DiscardUnknown(m)
}

var xxx_messageInfo_Red proto.InternalMessageInfo

func (m *Red) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Red) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Red) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Red) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Red) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Red) GetPoint() float64 {
	if m != nil {
		return m.Point
	}
	return 0
}

type GetRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetResponse struct {
	Red                  *Red     `protobuf:"bytes,1,opt,name=red,proto3" json:"red,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetRed() *Red {
	if m != nil {
		return m.Red
	}
	return nil
}

type ListRequest struct {
	Offset               int32              `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32              `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Size                 Size               `protobuf:"varint,3,opt,name=size,proto3,enum=red.Size" json:"size,omitempty"`
	Filters              []ListRequest_Type `protobuf:"varint,4,rep,packed,name=filters,proto3,enum=red.ListRequest_Type" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetSize() Size {
	if m != nil {
		return m.Size
	}
	return Size_SMALL
}

func (m *ListRequest) GetFilters() []ListRequest_Type {
	if m != nil {
		return m.Filters
	}
	return nil
}

type ListResponse struct {
	Reds                 []*Red   `protobuf:"bytes,1,rep,name=reds,proto3" json:"reds,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Size                 int32    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetReds() []*Red {
	if m != nil {
		return m.Reds
	}
	return nil
}

func (m *ListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListResponse) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type CreateRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{5}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateResponse struct {
	Red                  *Red     `protobuf:"bytes,1,opt,name=red,proto3" json:"red,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{6}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetRed() *Red {
	if m != nil {
		return m.Red
	}
	return nil
}

type UpdateRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{7}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateResponse struct {
	Red                  *Red     `protobuf:"bytes,1,opt,name=red,proto3" json:"red,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{8}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetRed() *Red {
	if m != nil {
		return m.Red
	}
	return nil
}

type DeleteRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{9}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_167dd47d2b98bb3b, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("red.Size", Size_name, Size_value)
	proto.RegisterEnum("red.ListRequest_Type", ListRequest_Type_name, ListRequest_Type_value)
	proto.RegisterType((*Red)(nil), "red.Red")
	proto.RegisterType((*GetRequest)(nil), "red.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "red.GetResponse")
	proto.RegisterType((*ListRequest)(nil), "red.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "red.ListResponse")
	proto.RegisterType((*CreateRequest)(nil), "red.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "red.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "red.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "red.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "red.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "red.DeleteResponse")
}

func init() { proto.RegisterFile("proto/red/red.proto", fileDescriptor_167dd47d2b98bb3b) }

var fileDescriptor_167dd47d2b98bb3b = []byte{
	// 648 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x41, 0x4f, 0xdb, 0x4c,
	0x10, 0xc5, 0xb1, 0x63, 0xc8, 0xe4, 0x4b, 0xc8, 0xb7, 0xd0, 0xca, 0x8d, 0xa0, 0x5d, 0xed, 0xc9,
	0x6d, 0x4a, 0x90, 0x42, 0xff, 0x40, 0x68, 0x22, 0xd4, 0x36, 0xa4, 0x62, 0x53, 0xd4, 0x63, 0x65,
	0xb2, 0x43, 0xb0, 0x64, 0x62, 0x63, 0x6f, 0x8a, 0xe0, 0x8f, 0x70, 0xcf, 0xbd, 0xc7, 0xfc, 0xbf,
	0x6a, 0xd7, 0xeb, 0x06, 0x23, 0x55, 0xa2, 0x87, 0x48, 0x33, 0x6f, 0x67, 0xde, 0xcc, 0xdb, 0xb7,
	0x31, 0xec, 0x24, 0x69, 0x2c, 0xe3, 0xc3, 0x14, 0x85, 0xfa, 0x75, 0x75, 0x46, 0xec, 0x14, 0x45,
	0xfb, 0xc3, 0x2c, 0x94, 0x57, 0x8b, 0x8b, 0xee, 0x34, 0xbe, 0x3e, 0x9c, 0xa5, 0xc9, 0xf4, 0x60,
	0xba, 0xc8, 0xa4, 0x8e, 0x83, 0xe4, 0xea, 0x26, 0x3a, 0x98, 0x05, 0x12, 0x6f, 0x83, 0xbb, 0x22,
	0xcf, 0x5b, 0xd9, 0x83, 0x05, 0x36, 0x47, 0x41, 0x9a, 0x50, 0x09, 0x85, 0x67, 0x51, 0xcb, 0xaf,
	0xf2, 0x4a, 0x28, 0x08, 0x01, 0x67, 0x1e, 0x5c, 0xa3, 0x57, 0xa1, 0x96, 0x5f, 0xe3, 0x3a, 0x26,
	0xfb, 0x00, 0xd3, 0x14, 0x03, 0x89, 0xe2, 0x47, 0x20, 0x3d, 0x9b, 0x5a, 0xbe, 0xcd, 0x6b, 0x06,
	0xe9, 0x4b, 0x75, 0xbc, 0x48, 0x44, 0x71, 0xec, 0xe4, 0xc7, 0x06, 0xe9, 0x4b, 0xe2, 0xc1, 0x26,
	0xce, 0x83, 0x8b, 0x08, 0x85, 0x57, 0xa5, 0x96, 0xbf, 0xc5, 0x8b, 0x94, 0xec, 0x42, 0x35, 0x89,
	0xc3, 0xb9, 0xf4, 0x5c, 0x6a, 0xf9, 0x16, 0xcf, 0x13, 0xc6, 0x00, 0x4e, 0x50, 0x72, 0xbc, 0x59,
	0x60, 0x26, 0xc9, 0xee, 0x7a, 0xbf, 0x63, 0x67, 0xb9, 0xea, 0x6c, 0xa8, 0x2d, 0xd9, 0x5b, 0xa8,
	0xeb, 0x9a, 0x2c, 0x89, 0xe7, 0x19, 0x92, 0x36, 0xa8, 0x9b, 0xd0, 0x55, 0xf5, 0xde, 0x56, 0x57,
	0x5d, 0x10, 0x47, 0xc1, 0x15, 0xc8, 0x7e, 0x59, 0x50, 0x1f, 0x85, 0xd9, 0x1f, 0xc2, 0x97, 0xe0,
	0xc6, 0x97, 0x97, 0x19, 0x4a, 0x23, 0xda, 0x64, 0x6a, 0x99, 0x28, 0xbc, 0x0e, 0xa5, 0x56, 0x5e,
	0xe5, 0x79, 0x42, 0xf6, 0xc1, 0xc9, 0xc2, 0x7b, 0xd4, 0xa2, 0x9b, 0xbd, 0x9a, 0xa6, 0x9e, 0x84,
	0xf7, 0xc8, 0x35, 0x4c, 0x0e, 0x61, 0xf3, 0x32, 0x8c, 0x24, 0xa6, 0x99, 0xe7, 0x50, 0xdb, 0x6f,
	0xf6, 0x5e, 0xe8, 0x8a, 0x47, 0xf3, 0xba, 0xdf, 0xee, 0x12, 0xe4, 0x45, 0x15, 0xa3, 0xe0, 0x28,
	0x80, 0xd4, 0x61, 0xf3, 0x7c, 0xfc, 0x65, 0xfc, 0xf5, 0xfb, 0xb8, 0xb5, 0xa1, 0x92, 0xe1, 0xb8,
	0x7f, 0x3c, 0x1a, 0x0e, 0x5a, 0x16, 0x8b, 0xe0, 0xbf, 0xbc, 0xdd, 0x68, 0xdb, 0x03, 0x27, 0x45,
	0x91, 0x79, 0x16, 0xb5, 0x4b, 0xe2, 0x34, 0xaa, 0xb6, 0x96, 0xb1, 0x0c, 0xa2, 0x62, 0x6b, 0x9d,
	0xac, 0xb5, 0xd8, 0x8f, 0xb5, 0x10, 0xa3, 0xc5, 0xd1, 0xa0, 0x8e, 0xd9, 0x11, 0x34, 0x3e, 0x6a,
	0x23, 0x8b, 0xeb, 0x79, 0xc6, 0x7b, 0x60, 0xef, 0xa1, 0x59, 0x34, 0x3d, 0xc3, 0x80, 0x23, 0x68,
	0x9c, 0xeb, 0xc7, 0xf0, 0x8f, 0x23, 0x8a, 0xa6, 0x67, 0x8c, 0x78, 0x03, 0x8d, 0x01, 0x46, 0xf8,
	0xd7, 0x11, 0x8c, 0x42, 0xb3, 0x28, 0x30, 0x74, 0x4f, 0x2a, 0xde, 0xf9, 0xe0, 0x28, 0x5f, 0x49,
	0x0d, 0xaa, 0x93, 0xd3, 0xfe, 0x68, 0xd4, 0xda, 0x20, 0x00, 0xee, 0xe9, 0xa7, 0xc1, 0x60, 0x34,
	0x6c, 0x59, 0x0a, 0x1e, 0xf5, 0xf9, 0xc9, 0xb0, 0x55, 0xe9, 0x3d, 0xd8, 0x00, 0x1c, 0xc5, 0x04,
	0xd3, 0x9f, 0xe1, 0x14, 0xc9, 0x31, 0xd8, 0x27, 0x28, 0xc9, 0xb6, 0xde, 0x68, 0xfd, 0x70, 0xdb,
	0xad, 0x35, 0x90, 0x8f, 0x64, 0xde, 0x72, 0xd5, 0xd9, 0x05, 0x77, 0xa6, 0x20, 0xc1, 0x60, 0x86,
	0x32, 0xa3, 0x01, 0x4d, 0x51, 0x90, 0xcf, 0xe0, 0x28, 0xcf, 0x49, 0xeb, 0xe9, 0xeb, 0x69, 0xff,
	0xff, 0x08, 0x31, 0x34, 0xfb, 0xcb, 0x55, 0xe7, 0x15, 0x6c, 0x45, 0x1a, 0x13, 0x19, 0x6b, 0xa8,
	0x48, 0xd1, 0x50, 0x11, 0xc8, 0x80, 0x4c, 0xc0, 0xcd, 0xcd, 0x21, 0x44, 0xf7, 0x96, 0xec, 0x6d,
	0xef, 0x94, 0x30, 0xc3, 0x48, 0x97, 0xab, 0xce, 0x1e, 0x31, 0xff, 0x68, 0xb5, 0xdb, 0x76, 0x1e,
	0x66, 0x74, 0x8e, 0xb7, 0x7a, 0xc1, 0x33, 0x70, 0x73, 0x3b, 0x0c, 0x69, 0xc9, 0x50, 0x43, 0x5a,
	0xf6, 0x8b, 0xbd, 0x5e, 0xae, 0x3a, 0x6d, 0x62, 0xbe, 0x03, 0x8a, 0xb4, 0x91, 0x87, 0x85, 0xe6,
	0x33, 0x70, 0x73, 0x4b, 0x0c, 0x65, 0xc9, 0x40, 0x43, 0x59, 0xf6, 0xac, 0xa0, 0x14, 0x06, 0x15,
	0xac, 0x91, 0x87, 0x86, 0xf2, 0xc2, 0xd5, 0x9f, 0xb6, 0xa3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd6, 0x06, 0xd2, 0xb6, 0x2c, 0x05, 0x00, 0x00,
}
