// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/sample/proto/green/green.proto

package green

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-custom/graphql-gateway/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Term struct {
	StartAt              int64    `protobuf:"varint,1,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                int64    `protobuf:"varint,2,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Term) Reset()         { *m = Term{} }
func (m *Term) String() string { return proto.CompactTextString(m) }
func (*Term) ProtoMessage()    {}
func (*Term) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d525c94755f64be, []int{0}
}

func (m *Term) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Term.Unmarshal(m, b)
}
func (m *Term) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Term.Marshal(b, m, deterministic)
}
func (m *Term) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Term.Merge(m, src)
}
func (m *Term) XXX_Size() int {
	return xxx_messageInfo_Term.Size(m)
}
func (m *Term) XXX_DiscardUnknown() {
	xxx_messageInfo_Term.DiscardUnknown(m)
}

var xxx_messageInfo_Term proto.InternalMessageInfo

func (m *Term) GetStartAt() int64 {
	if m != nil {
		return m.StartAt
	}
	return 0
}

func (m *Term) GetEndAt() int64 {
	if m != nil {
		return m.EndAt
	}
	return 0
}

type Green struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text                 string               `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Url                  string               `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Term                 *Term                `protobuf:"bytes,7,opt,name=term,proto3" json:"term,omitempty"`
	Published            bool                 `protobuf:"varint,8,opt,name=published,proto3" json:"published,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Green) Reset()         { *m = Green{} }
func (m *Green) String() string { return proto.CompactTextString(m) }
func (*Green) ProtoMessage()    {}
func (*Green) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d525c94755f64be, []int{1}
}

func (m *Green) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Green.Unmarshal(m, b)
}
func (m *Green) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Green.Marshal(b, m, deterministic)
}
func (m *Green) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Green.Merge(m, src)
}
func (m *Green) XXX_Size() int {
	return xxx_messageInfo_Green.Size(m)
}
func (m *Green) XXX_DiscardUnknown() {
	xxx_messageInfo_Green.DiscardUnknown(m)
}

var xxx_messageInfo_Green proto.InternalMessageInfo

func (m *Green) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Green) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Green) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Green) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Green) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Green) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Green) GetTerm() *Term {
	if m != nil {
		return m.Term
	}
	return nil
}

func (m *Green) GetPublished() bool {
	if m != nil {
		return m.Published
	}
	return false
}

type ListRequest struct {
	NextToken            string   `protobuf:"bytes,1,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d525c94755f64be, []int{2}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetNextToken() string {
	if m != nil {
		return m.NextToken
	}
	return ""
}

func (m *ListRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ListResponse struct {
	NextToken            string   `protobuf:"bytes,1,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	Greens               []*Green `protobuf:"bytes,2,rep,name=greens,proto3" json:"greens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d525c94755f64be, []int{3}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetNextToken() string {
	if m != nil {
		return m.NextToken
	}
	return ""
}

func (m *ListResponse) GetGreens() []*Green {
	if m != nil {
		return m.Greens
	}
	return nil
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d525c94755f64be, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Green                *Green   `protobuf:"bytes,1,opt,name=green,proto3" json:"green,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d525c94755f64be, []int{5}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetGreen() *Green {
	if m != nil {
		return m.Green
	}
	return nil
}

func init() {
	proto.RegisterType((*Term)(nil), "green.Term")
	proto.RegisterType((*Green)(nil), "green.Green")
	proto.RegisterType((*ListRequest)(nil), "green.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "green.ListResponse")
	proto.RegisterType((*GetRequest)(nil), "green.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "green.GetResponse")
}

func init() {
	proto.RegisterFile("example/sample/proto/green/green.proto", fileDescriptor_5d525c94755f64be)
}

var fileDescriptor_5d525c94755f64be = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0x9c, 0x38, 0x8d, 0xc7, 0x51, 0x55, 0x16, 0x90, 0x8c, 0x55, 0x54, 0xcb, 0x42, 0x28,
	0x52, 0x55, 0x47, 0x04, 0x0e, 0x20, 0x71, 0x31, 0x97, 0x70, 0xe0, 0xe4, 0xe6, 0x5e, 0x39, 0xf6,
	0xe0, 0xac, 0xf0, 0x5f, 0xbd, 0x63, 0x08, 0x3c, 0x01, 0x37, 0xde, 0x21, 0xef, 0x90, 0xf7, 0x43,
	0x9e, 0xb5, 0x4b, 0xe9, 0xa5, 0x97, 0x64, 0xe7, 0xfb, 0x99, 0xf9, 0x76, 0xd6, 0xf0, 0x1a, 0xf7,
	0x71, 0x51, 0xe7, 0xb8, 0x54, 0xfa, 0xaf, 0x6e, 0x2a, 0xaa, 0x96, 0x59, 0x83, 0x58, 0xea, 0xdf,
	0x80, 0x11, 0x61, 0x72, 0xe1, 0x5e, 0x64, 0x55, 0x95, 0x0d, 0xb2, 0x6d, 0xfb, 0x75, 0x49, 0xb2,
	0x40, 0x45, 0x71, 0x51, 0x6b, 0x9d, 0xfb, 0x2e, 0x93, 0xb4, 0x6b, 0xb7, 0x41, 0x52, 0x15, 0xcb,
	0xac, 0xa9, 0x93, 0xab, 0xa4, 0x55, 0xc4, 0xe7, 0xb8, 0xde, 0xdd, 0xe6, 0x57, 0x59, 0x4c, 0xf8,
	0x23, 0xfe, 0x39, 0xd4, 0xda, 0xe5, 0xbf, 0x87, 0xc9, 0x06, 0x9b, 0x42, 0xbc, 0x80, 0x99, 0xa2,
	0xb8, 0xa1, 0x9b, 0x98, 0x9c, 0x91, 0x37, 0x5a, 0x8c, 0xa3, 0x13, 0xae, 0x43, 0x12, 0xcf, 0x61,
	0x8a, 0x65, 0xda, 0x11, 0x06, 0x13, 0x26, 0x96, 0x69, 0x48, 0xfe, 0x6f, 0x03, 0xcc, 0x75, 0x17,
	0x4d, 0x9c, 0x82, 0x21, 0x53, 0x76, 0x59, 0x91, 0x21, 0x53, 0xf1, 0x0c, 0x4c, 0x92, 0x94, 0x23,
	0xeb, 0xad, 0x48, 0x17, 0x42, 0xc0, 0x84, 0x70, 0x4f, 0xce, 0x98, 0x41, 0x3e, 0x8b, 0x33, 0x18,
	0xb7, 0x4d, 0xee, 0x4c, 0x18, 0xea, 0x8e, 0xe2, 0x03, 0x40, 0xd2, 0x60, 0x4c, 0xc8, 0x03, 0x4d,
	0x6f, 0xb4, 0xb0, 0x57, 0x6e, 0xa0, 0xef, 0x1e, 0x0c, 0x77, 0x0f, 0x36, 0xc3, 0xdd, 0x23, 0xab,
	0x57, 0x87, 0xd4, 0x59, 0xdb, 0x3a, 0x1d, 0xac, 0xd3, 0xc7, 0xad, 0xbd, 0x3a, 0x24, 0x71, 0xd1,
	0x65, 0x6b, 0x0a, 0xe7, 0x84, 0x4d, 0x76, 0xa0, 0xf7, 0xdf, 0x2d, 0x26, 0x62, 0x42, 0x9c, 0x83,
	0x55, 0xb7, 0xdb, 0x5c, 0xaa, 0x1d, 0xa6, 0xce, 0xcc, 0x1b, 0x2d, 0x66, 0xd1, 0x3f, 0xc0, 0xff,
	0x0c, 0xf6, 0x17, 0xa9, 0x28, 0xc2, 0xdb, 0x16, 0x15, 0x89, 0x97, 0x00, 0x25, 0xee, 0xe9, 0x86,
	0xaa, 0x6f, 0x58, 0xf6, 0x7b, 0xb1, 0x3a, 0x64, 0xd3, 0x01, 0xc2, 0x85, 0x89, 0x92, 0xbf, 0xf4,
	0x76, 0xcc, 0x4f, 0xd3, 0xc3, 0xf1, 0xd2, 0xf0, 0xd2, 0x88, 0x31, 0xff, 0x1a, 0xe6, 0xba, 0x93,
	0xaa, 0xab, 0x52, 0xe1, 0x63, 0xad, 0x5e, 0xc1, 0x94, 0xa3, 0x2a, 0xc7, 0xf0, 0xc6, 0x0b, 0x7b,
	0x35, 0xef, 0x93, 0xf3, 0xbb, 0x44, 0x3d, 0xe7, 0x9f, 0x03, 0xac, 0xf1, 0x2e, 0xdd, 0x83, 0xd7,
	0xf2, 0xdf, 0x80, 0xcd, 0x6c, 0x3f, 0xd1, 0x07, 0xfd, 0xc1, 0xb1, 0xe2, 0x61, 0x47, 0x4d, 0xad,
	0xfe, 0x8c, 0x60, 0xce, 0xc0, 0x35, 0x36, 0xdf, 0x65, 0x82, 0x22, 0x84, 0x49, 0x17, 0x5b, 0x88,
	0x5e, 0x7d, 0x6f, 0x1b, 0xee, 0xd3, 0xff, 0x30, 0x3d, 0xc5, 0x3f, 0x3b, 0x1c, 0x2f, 0xe7, 0x00,
	0xb9, 0x54, 0xc4, 0x8d, 0x94, 0xf8, 0x08, 0xe3, 0x35, 0x92, 0x78, 0x32, 0xcc, 0xbb, 0x0b, 0xec,
	0x8a, 0xfb, 0x50, 0xef, 0x3f, 0x3d, 0x1c, 0x2f, 0x01, 0x66, 0x19, 0x6a, 0xfb, 0x76, 0xca, 0xef,
	0xfb, 0xf6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0x11, 0xa3, 0x8b, 0x55, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreenServiceClient is the client API for GreenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreenServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type greenServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreenServiceClient(cc *grpc.ClientConn) GreenServiceClient {
	return &greenServiceClient{cc}
}

func (c *greenServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/green.GreenService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greenServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/green.GreenService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreenServiceServer is the server API for GreenService service.
type GreenServiceServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterGreenServiceServer(s *grpc.Server, srv GreenServiceServer) {
	s.RegisterService(&_GreenService_serviceDesc, srv)
}

func _GreenService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/green.GreenService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreenService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/green.GreenService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "green.GreenService",
	HandlerType: (*GreenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _GreenService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GreenService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/sample/proto/green/green.proto",
}
