// Code generated by protoc-gen-graphql-gateway. DO NOT EDIT.
// source: example/photo_share/proto/user/user.proto

/*
Package user is a reverse proxy.

It translates gRPC into GraphQL.
*/
package user

import (
	"context"

	"github.com/golang/protobuf/ptypes/empty"
	"github.com/graphql-go/graphql"
	"github.com/grpc-custom/graphql-gateway/runtime"
	"github.com/grpc-custom/graphql-gateway/runtime/scalar"
	"google.golang.org/grpc"
	"google.golang.org/grpc/grpclog"
)

var (
	userType = graphql.NewObject(graphql.ObjectConfig{
		Name: "User",
		Fields: graphql.Fields{
			"githubLogin": &graphql.Field{
				Type: scalar.String,
			},
			"name": &graphql.Field{
				Type: scalar.String,
			},
			"avatar": &graphql.Field{
				Type: scalar.String,
			},
		},
	})

	userResponseType = graphql.NewObject(graphql.ObjectConfig{
		Name: "UserResponse",
		Fields: graphql.Fields{
			"user": &graphql.Field{
				Type: userType,
			},
		},
	})

	totalUsersResponseType = graphql.NewObject(graphql.ObjectConfig{
		Name: "TotalUsersResponse",
		Fields: graphql.Fields{
			"total": &graphql.Field{
				Type: scalar.Int32,
			},
		},
	})

	allUsersResponseType = graphql.NewObject(graphql.ObjectConfig{
		Name: "AllUsersResponse",
		Fields: graphql.Fields{
			"users": &graphql.Field{
				Type: graphql.NewList(userType),
			},
		},
	})

	loginRequestType = graphql.NewObject(graphql.ObjectConfig{
		Name: "LoginRequest",
		Fields: graphql.Fields{
			"login": &graphql.Field{
				Type: scalar.String,
			},
		},
	})

	githubAuthRequestType = graphql.NewObject(graphql.ObjectConfig{
		Name: "GithubAuthRequest",
		Fields: graphql.Fields{
			"code": &graphql.Field{
				Type: scalar.String,
			},
		},
	})

	githubAuthResponseType = graphql.NewObject(graphql.ObjectConfig{
		Name: "GithubAuthResponse",
		Fields: graphql.Fields{
			"token": &graphql.Field{
				Type: scalar.String,
			},
			"user": &graphql.Field{
				Type: userType,
			},
		},
	})
)

func RegisterUserServerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return
	}
	defer func() {
		if err != nil {
			if e := conn.Close(); e != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, e)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if e := conn.Close(); e != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, e)
			}
		}()
	}()
	return RegisterUserServerHandler(mux, conn)
}

func RegisterUserServerHandler(mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterUserServerHandlerClient(mux, NewUserServerClient(conn))
}

func RegisterUserServerHandlerClient(mux *runtime.ServeMux, client UserServerClient) error {
	// gRPC /user.UserServer/Me
	meField := &graphql.Field{
		Name:        "/user.UserServer/Me",
		Description: "",
		Type:        userResponseType,
		Args:        graphql.FieldConfigArgument{},
		Resolve: func(p graphql.ResolveParams) (interface{}, error) {
			in := &empty.Empty{}
			ctx := runtime.Context(p.Context)
			return client.Me(ctx, in)
		},
	}
	mux.AddQuery("me", meField)
	// gRPC /user.UserServer/TotalUsers
	totalUsersField := &graphql.Field{
		Name:        "/user.UserServer/TotalUsers",
		Description: "",
		Type:        totalUsersResponseType,
		Args:        graphql.FieldConfigArgument{},
		Resolve: func(p graphql.ResolveParams) (interface{}, error) {
			in := &empty.Empty{}
			ctx := runtime.Context(p.Context)
			return client.TotalUsers(ctx, in)
		},
	}
	mux.AddQuery("totalUsers", totalUsersField)
	// gRPC /user.UserServer/AllUsers
	allUsersField := &graphql.Field{
		Name:        "/user.UserServer/AllUsers",
		Description: "",
		Type:        allUsersResponseType,
		Args:        graphql.FieldConfigArgument{},
		Resolve: func(p graphql.ResolveParams) (interface{}, error) {
			in := &empty.Empty{}
			ctx := runtime.Context(p.Context)
			return client.AllUsers(ctx, in)
		},
	}
	mux.AddQuery("allUsers", allUsersField)
	// gRPC /user.UserServer/User
	userField := &graphql.Field{
		Name:        "/user.UserServer/User",
		Description: "",
		Type:        userResponseType,
		Args: graphql.FieldConfigArgument{
			"login": &graphql.ArgumentConfig{
				Type: scalar.String,
			},
		},
		Resolve: func(p graphql.ResolveParams) (interface{}, error) {
			in := &LoginRequest{}
			valueLogin, ok := p.Args["login"].(string)
			if !ok {
				valueLogin = ""
			}
			in.Login = valueLogin
			ctx := runtime.Context(p.Context)
			return client.User(ctx, in)
		},
	}
	mux.AddQuery("user", userField)
	// gRPC /user.UserServer/GithubAuth
	githubAuthField := &graphql.Field{
		Name:        "/user.UserServer/GithubAuth",
		Description: "",
		Type:        githubAuthResponseType,
		Args: graphql.FieldConfigArgument{
			"code": &graphql.ArgumentConfig{
				Type: scalar.String,
			},
		},
		Resolve: func(p graphql.ResolveParams) (interface{}, error) {
			in := &GithubAuthRequest{}
			valueCode, ok := p.Args["code"].(string)
			if !ok {
				valueCode = ""
			}
			in.Code = valueCode
			ctx := runtime.Context(p.Context)
			return client.GithubAuth(ctx, in)
		},
	}
	mux.AddMutation("githubAuth", githubAuthField)
	return nil
}
