// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graphql.proto

package graphql

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CacheControl struct {
	MaxAge               string   `protobuf:"bytes,1,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheControl) Reset()         { *m = CacheControl{} }
func (m *CacheControl) String() string { return proto.CompactTextString(m) }
func (*CacheControl) ProtoMessage()    {}
func (*CacheControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{0}
}

func (m *CacheControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheControl.Unmarshal(m, b)
}
func (m *CacheControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheControl.Marshal(b, m, deterministic)
}
func (m *CacheControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheControl.Merge(m, src)
}
func (m *CacheControl) XXX_Size() int {
	return xxx_messageInfo_CacheControl.Size(m)
}
func (m *CacheControl) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheControl.DiscardUnknown(m)
}

var xxx_messageInfo_CacheControl proto.InternalMessageInfo

func (m *CacheControl) GetMaxAge() string {
	if m != nil {
		return m.MaxAge
	}
	return ""
}

type Schema struct {
	// Types that are valid to be assigned to Type:
	//	*Schema_Query
	//	*Schema_Mutation
	//	*Schema_Subscribe
	//	*Schema_Extend
	Type                 isSchema_Type `protobuf_oneof:"type"`
	Description          string        `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CacheControl         *CacheControl `protobuf:"bytes,7,opt,name=cache_control,json=cacheControl,proto3" json:"cache_control,omitempty"`
	Field                string        `protobuf:"bytes,8,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{1}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

type isSchema_Type interface {
	isSchema_Type()
}

type Schema_Query struct {
	Query string `protobuf:"bytes,1,opt,name=query,proto3,oneof"`
}

type Schema_Mutation struct {
	Mutation string `protobuf:"bytes,2,opt,name=mutation,proto3,oneof"`
}

type Schema_Subscribe struct {
	Subscribe string `protobuf:"bytes,3,opt,name=subscribe,proto3,oneof"`
}

type Schema_Extend struct {
	Extend string `protobuf:"bytes,4,opt,name=extend,proto3,oneof"`
}

func (*Schema_Query) isSchema_Type() {}

func (*Schema_Mutation) isSchema_Type() {}

func (*Schema_Subscribe) isSchema_Type() {}

func (*Schema_Extend) isSchema_Type() {}

func (m *Schema) GetType() isSchema_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Schema) GetQuery() string {
	if x, ok := m.GetType().(*Schema_Query); ok {
		return x.Query
	}
	return ""
}

func (m *Schema) GetMutation() string {
	if x, ok := m.GetType().(*Schema_Mutation); ok {
		return x.Mutation
	}
	return ""
}

func (m *Schema) GetSubscribe() string {
	if x, ok := m.GetType().(*Schema_Subscribe); ok {
		return x.Subscribe
	}
	return ""
}

func (m *Schema) GetExtend() string {
	if x, ok := m.GetType().(*Schema_Extend); ok {
		return x.Extend
	}
	return ""
}

func (m *Schema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Schema) GetCacheControl() *CacheControl {
	if m != nil {
		return m.CacheControl
	}
	return nil
}

func (m *Schema) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Schema) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Schema_OneofMarshaler, _Schema_OneofUnmarshaler, _Schema_OneofSizer, []interface{}{
		(*Schema_Query)(nil),
		(*Schema_Mutation)(nil),
		(*Schema_Subscribe)(nil),
		(*Schema_Extend)(nil),
	}
}

func _Schema_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Schema)
	// type
	switch x := m.Type.(type) {
	case *Schema_Query:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Query)
	case *Schema_Mutation:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Mutation)
	case *Schema_Subscribe:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Subscribe)
	case *Schema_Extend:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Extend)
	case nil:
	default:
		return fmt.Errorf("Schema.Type has unexpected type %T", x)
	}
	return nil
}

func _Schema_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Schema)
	switch tag {
	case 1: // type.query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Type = &Schema_Query{x}
		return true, err
	case 2: // type.mutation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Type = &Schema_Mutation{x}
		return true, err
	case 3: // type.subscribe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Type = &Schema_Subscribe{x}
		return true, err
	case 4: // type.extend
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Type = &Schema_Extend{x}
		return true, err
	default:
		return false, nil
	}
}

func _Schema_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Schema)
	// type
	switch x := m.Type.(type) {
	case *Schema_Query:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Query)))
		n += len(x.Query)
	case *Schema_Mutation:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Mutation)))
		n += len(x.Mutation)
	case *Schema_Subscribe:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Subscribe)))
		n += len(x.Subscribe)
	case *Schema_Extend:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Extend)))
		n += len(x.Extend)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Field struct {
	Nullable    bool   `protobuf:"varint,1,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Default:
	//	*Field_DefaultString
	//	*Field_DefaultNumber
	//	*Field_DefaultBool
	Default              isField_Default `protobuf_oneof:"default"`
	Inline               bool            `protobuf:"varint,6,opt,name=inline,proto3" json:"inline,omitempty"`
	Name                 string          `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Exclude              bool            `protobuf:"varint,8,opt,name=exclude,proto3" json:"exclude,omitempty"`
	External             string          `protobuf:"bytes,9,opt,name=external,proto3" json:"external,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{2}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

func (m *Field) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type isField_Default interface {
	isField_Default()
}

type Field_DefaultString struct {
	DefaultString string `protobuf:"bytes,3,opt,name=default_string,json=defaultString,proto3,oneof"`
}

type Field_DefaultNumber struct {
	DefaultNumber int32 `protobuf:"varint,4,opt,name=default_number,json=defaultNumber,proto3,oneof"`
}

type Field_DefaultBool struct {
	DefaultBool bool `protobuf:"varint,5,opt,name=default_bool,json=defaultBool,proto3,oneof"`
}

func (*Field_DefaultString) isField_Default() {}

func (*Field_DefaultNumber) isField_Default() {}

func (*Field_DefaultBool) isField_Default() {}

func (m *Field) GetDefault() isField_Default {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *Field) GetDefaultString() string {
	if x, ok := m.GetDefault().(*Field_DefaultString); ok {
		return x.DefaultString
	}
	return ""
}

func (m *Field) GetDefaultNumber() int32 {
	if x, ok := m.GetDefault().(*Field_DefaultNumber); ok {
		return x.DefaultNumber
	}
	return 0
}

func (m *Field) GetDefaultBool() bool {
	if x, ok := m.GetDefault().(*Field_DefaultBool); ok {
		return x.DefaultBool
	}
	return false
}

func (m *Field) GetInline() bool {
	if m != nil {
		return m.Inline
	}
	return false
}

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetExclude() bool {
	if m != nil {
		return m.Exclude
	}
	return false
}

func (m *Field) GetExternal() string {
	if m != nil {
		return m.External
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Field) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Field_OneofMarshaler, _Field_OneofUnmarshaler, _Field_OneofSizer, []interface{}{
		(*Field_DefaultString)(nil),
		(*Field_DefaultNumber)(nil),
		(*Field_DefaultBool)(nil),
	}
}

func _Field_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Field)
	// default
	switch x := m.Default.(type) {
	case *Field_DefaultString:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.DefaultString)
	case *Field_DefaultNumber:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.DefaultNumber))
	case *Field_DefaultBool:
		t := uint64(0)
		if x.DefaultBool {
			t = 1
		}
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("Field.Default has unexpected type %T", x)
	}
	return nil
}

func _Field_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Field)
	switch tag {
	case 3: // default.default_string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Default = &Field_DefaultString{x}
		return true, err
	case 4: // default.default_number
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Default = &Field_DefaultNumber{int32(x)}
		return true, err
	case 5: // default.default_bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Default = &Field_DefaultBool{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _Field_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Field)
	// default
	switch x := m.Default.(type) {
	case *Field_DefaultString:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.DefaultString)))
		n += len(x.DefaultString)
	case *Field_DefaultNumber:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.DefaultNumber))
	case *Field_DefaultBool:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Object struct {
	Typename             string   `protobuf:"bytes,1,opt,name=typename,proto3" json:"typename,omitempty"`
	Key                  []string `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{3}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetTypename() string {
	if m != nil {
		return m.Typename
	}
	return ""
}

func (m *Object) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Object) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

var E_Schema = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Schema)(nil),
	Field:         88916,
	Name:          "grpc_custom.graphql.schema",
	Tag:           "bytes,88916,opt,name=schema",
	Filename:      "graphql.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Field)(nil),
	Field:         88916,
	Name:          "grpc_custom.graphql.field",
	Tag:           "bytes,88916,opt,name=field",
	Filename:      "graphql.proto",
}

var E_Object = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Object)(nil),
	Field:         88916,
	Name:          "grpc_custom.graphql.object",
	Tag:           "bytes,88916,opt,name=object",
	Filename:      "graphql.proto",
}

func init() {
	proto.RegisterType((*CacheControl)(nil), "grpc_custom.graphql.CacheControl")
	proto.RegisterType((*Schema)(nil), "grpc_custom.graphql.Schema")
	proto.RegisterType((*Field)(nil), "grpc_custom.graphql.Field")
	proto.RegisterType((*Object)(nil), "grpc_custom.graphql.Object")
	proto.RegisterExtension(E_Schema)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Object)
}

func init() { proto.RegisterFile("graphql.proto", fileDescriptor_3ce0fc368bdc1a51) }

var fileDescriptor_3ce0fc368bdc1a51 = []byte{
	// 548 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x6d, 0x93, 0xd8, 0xb1, 0x6f, 0x13, 0x84, 0x06, 0x54, 0x46, 0x01, 0x4a, 0x08, 0x8b, 0x66,
	0x53, 0x47, 0x02, 0xc4, 0x22, 0xac, 0x48, 0xa5, 0xaa, 0x1b, 0xa8, 0x70, 0x05, 0x42, 0x6c, 0xa2,
	0xb1, 0x7d, 0xe3, 0x18, 0xc6, 0x9e, 0xd4, 0x1e, 0x8b, 0x64, 0xc7, 0xef, 0xf0, 0x03, 0x7c, 0x09,
	0x1f, 0x84, 0xe6, 0x91, 0x10, 0x25, 0x59, 0xb0, 0xf3, 0x39, 0xf7, 0x7d, 0xe6, 0x18, 0xba, 0x69,
	0xc9, 0x16, 0xf3, 0x3b, 0x1e, 0x2c, 0x4a, 0x21, 0x05, 0x79, 0x90, 0x96, 0x8b, 0x78, 0x1a, 0xd7,
	0x95, 0x14, 0x79, 0x60, 0x43, 0xbd, 0x7e, 0x2a, 0x44, 0xca, 0x71, 0xa4, 0x53, 0xa2, 0x7a, 0x36,
	0x4a, 0xb0, 0x8a, 0xcb, 0x6c, 0x21, 0x45, 0x69, 0xca, 0x06, 0xe7, 0xd0, 0xb9, 0x64, 0xf1, 0x1c,
	0x2f, 0x45, 0x21, 0x4b, 0xc1, 0xc9, 0x23, 0x68, 0xe7, 0x6c, 0x39, 0x65, 0x29, 0xd2, 0xe3, 0xfe,
	0xf1, 0xd0, 0x0f, 0xdd, 0x9c, 0x2d, 0xdf, 0xa5, 0x38, 0xf8, 0xd9, 0x00, 0xf7, 0x36, 0x9e, 0x63,
	0xce, 0xc8, 0x29, 0x38, 0x77, 0x35, 0x96, 0x2b, 0x93, 0x71, 0x7d, 0x14, 0x1a, 0x48, 0x9e, 0x80,
	0x97, 0xd7, 0x92, 0xc9, 0x4c, 0x14, 0xb4, 0x61, 0x43, 0x1b, 0x86, 0x9c, 0x81, 0x5f, 0xd5, 0x91,
	0x1a, 0x1f, 0x21, 0x6d, 0xda, 0xf0, 0x3f, 0x8a, 0x50, 0x70, 0x71, 0x29, 0xb1, 0x48, 0x68, 0xcb,
	0x06, 0x2d, 0x26, 0x7d, 0x38, 0x59, 0xef, 0xad, 0x5a, 0xbb, 0x7a, 0xaf, 0x6d, 0x8a, 0x5c, 0x41,
	0x37, 0x56, 0x57, 0x4c, 0x63, 0x73, 0x06, 0x6d, 0xf7, 0x8f, 0x87, 0x27, 0x2f, 0x9f, 0x07, 0x07,
	0x44, 0x09, 0xb6, 0xef, 0x0d, 0x3b, 0xf1, 0xf6, 0xf5, 0x0f, 0xc1, 0x99, 0x65, 0xc8, 0x13, 0xea,
	0xe9, 0x19, 0x06, 0x4c, 0x5c, 0x68, 0xc9, 0xd5, 0x02, 0x07, 0xbf, 0x1a, 0xe0, 0x5c, 0x29, 0x86,
	0xf4, 0xc0, 0x2b, 0x6a, 0xce, 0x59, 0xc4, 0x8d, 0x4c, 0x5e, 0xb8, 0xc1, 0xbb, 0xdb, 0x36, 0xf6,
	0xb7, 0x3d, 0x87, 0x7b, 0x09, 0xce, 0x58, 0xcd, 0xe5, 0xb4, 0x92, 0x65, 0x56, 0xa4, 0x1b, 0x39,
	0xba, 0x96, 0xbf, 0xd5, 0xf4, 0x76, 0x62, 0x51, 0xe7, 0x11, 0x96, 0x5a, 0x1a, 0x67, 0x2b, 0xf1,
	0x83, 0xa6, 0xc9, 0x0b, 0xe8, 0xac, 0x13, 0x23, 0x21, 0x38, 0x75, 0xd4, 0x4e, 0xd7, 0x47, 0x6a,
	0xac, 0x66, 0x27, 0x42, 0x70, 0x72, 0x0a, 0x6e, 0x56, 0xf0, 0xac, 0x40, 0xad, 0xa0, 0x17, 0x5a,
	0x44, 0x08, 0xb4, 0x0a, 0x96, 0xa3, 0xd6, 0xcc, 0x0f, 0xf5, 0x37, 0xa1, 0xd0, 0xc6, 0x65, 0xcc,
	0xeb, 0x04, 0xb5, 0x14, 0x5e, 0xb8, 0x86, 0xea, 0x74, 0xf5, 0x2c, 0x65, 0xc1, 0x38, 0xf5, 0x75,
	0xc5, 0x06, 0x4f, 0x7c, 0x68, 0xdb, 0x81, 0x83, 0x2f, 0xe0, 0xde, 0x44, 0xdf, 0x30, 0x96, 0xaa,
	0x40, 0xa9, 0xa7, 0x47, 0x18, 0x4b, 0x6d, 0x30, 0xb9, 0x0f, 0xcd, 0xef, 0xb8, 0xa2, 0x8d, 0x7e,
	0x73, 0xe8, 0x87, 0xea, 0x73, 0x57, 0xbd, 0xe6, 0x9e, 0x7a, 0xe3, 0x4f, 0xe0, 0x56, 0xc6, 0x87,
	0x67, 0x81, 0xb1, 0x77, 0xb0, 0xb6, 0x77, 0xf0, 0x1e, 0xe5, 0x5c, 0x24, 0x37, 0x3a, 0xb1, 0xa2,
	0x7f, 0x7e, 0x3b, 0xda, 0x06, 0x8f, 0x0f, 0xda, 0xc0, 0x98, 0x39, 0xb4, 0xcd, 0xc6, 0x1f, 0xed,
	0xd3, 0x93, 0xa7, 0x7b, 0x5d, 0xf5, 0x9b, 0xef, 0x36, 0xed, 0x1d, 0x6c, 0xaa, 0x53, 0xad, 0x6f,
	0xc6, 0x9f, 0xc1, 0x15, 0x46, 0x83, 0x67, 0x07, 0x36, 0xad, 0x2a, 0x96, 0xe2, 0xff, 0xad, 0x6a,
	0x94, 0x0c, 0x6d, 0xb7, 0xc9, 0x9b, 0xaf, 0xaf, 0xd3, 0x4c, 0xce, 0xeb, 0x28, 0x88, 0x45, 0x3e,
	0x52, 0x05, 0x17, 0xa6, 0x60, 0x64, 0x0b, 0x2e, 0x52, 0x26, 0xf1, 0x07, 0x5b, 0x99, 0xff, 0xfe,
	0xad, 0x65, 0x23, 0x57, 0xc3, 0x57, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xb5, 0x49, 0xf6,
	0x3a, 0x04, 0x00, 0x00,
}
