// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graphql.proto

package graphql

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Scalar int32

const (
	// ProtocolBuffers scalar value types
	Scalar_BOOL   Scalar = 0
	Scalar_STRING Scalar = 1
	Scalar_INT32  Scalar = 2
	Scalar_UINT32 Scalar = 3
	Scalar_INT64  Scalar = 4
	Scalar_UINT64 Scalar = 5
	Scalar_FLOAT  Scalar = 6
	Scalar_DOUBLE Scalar = 7
	Scalar_BYTES  Scalar = 8
)

var Scalar_name = map[int32]string{
	0: "BOOL",
	1: "STRING",
	2: "INT32",
	3: "UINT32",
	4: "INT64",
	5: "UINT64",
	6: "FLOAT",
	7: "DOUBLE",
	8: "BYTES",
}

var Scalar_value = map[string]int32{
	"BOOL":   0,
	"STRING": 1,
	"INT32":  2,
	"UINT32": 3,
	"INT64":  4,
	"UINT64": 5,
	"FLOAT":  6,
	"DOUBLE": 7,
	"BYTES":  8,
}

func (x Scalar) String() string {
	return proto.EnumName(Scalar_name, int32(x))
}

func (Scalar) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{0}
}

type Schema struct {
	// Types that are valid to be assigned to Type:
	//	*Schema_Query
	//	*Schema_Mutation
	//	*Schema_Subscribe
	Type                 isSchema_Type `protobuf_oneof:"type"`
	Description          string        `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{0}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

type isSchema_Type interface {
	isSchema_Type()
}

type Schema_Query struct {
	Query string `protobuf:"bytes,1,opt,name=query,proto3,oneof"`
}

type Schema_Mutation struct {
	Mutation string `protobuf:"bytes,2,opt,name=mutation,proto3,oneof"`
}

type Schema_Subscribe struct {
	Subscribe string `protobuf:"bytes,3,opt,name=subscribe,proto3,oneof"`
}

func (*Schema_Query) isSchema_Type() {}

func (*Schema_Mutation) isSchema_Type() {}

func (*Schema_Subscribe) isSchema_Type() {}

func (m *Schema) GetType() isSchema_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Schema) GetQuery() string {
	if x, ok := m.GetType().(*Schema_Query); ok {
		return x.Query
	}
	return ""
}

func (m *Schema) GetMutation() string {
	if x, ok := m.GetType().(*Schema_Mutation); ok {
		return x.Mutation
	}
	return ""
}

func (m *Schema) GetSubscribe() string {
	if x, ok := m.GetType().(*Schema_Subscribe); ok {
		return x.Subscribe
	}
	return ""
}

func (m *Schema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Schema) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Schema_OneofMarshaler, _Schema_OneofUnmarshaler, _Schema_OneofSizer, []interface{}{
		(*Schema_Query)(nil),
		(*Schema_Mutation)(nil),
		(*Schema_Subscribe)(nil),
	}
}

func _Schema_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Schema)
	// type
	switch x := m.Type.(type) {
	case *Schema_Query:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Query)
	case *Schema_Mutation:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Mutation)
	case *Schema_Subscribe:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Subscribe)
	case nil:
	default:
		return fmt.Errorf("Schema.Type has unexpected type %T", x)
	}
	return nil
}

func _Schema_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Schema)
	switch tag {
	case 1: // type.query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Type = &Schema_Query{x}
		return true, err
	case 2: // type.mutation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Type = &Schema_Mutation{x}
		return true, err
	case 3: // type.subscribe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Type = &Schema_Subscribe{x}
		return true, err
	default:
		return false, nil
	}
}

func _Schema_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Schema)
	// type
	switch x := m.Type.(type) {
	case *Schema_Query:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Query)))
		n += len(x.Query)
	case *Schema_Mutation:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Mutation)))
		n += len(x.Mutation)
	case *Schema_Subscribe:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Subscribe)))
		n += len(x.Subscribe)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Field struct {
	Scalar               Scalar   `protobuf:"varint,1,opt,name=scalar,proto3,enum=graphql.Scalar" json:"scalar,omitempty"`
	Nullable             bool     `protobuf:"varint,2,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{1}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetScalar() Scalar {
	if m != nil {
		return m.Scalar
	}
	return Scalar_BOOL
}

func (m *Field) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

func (m *Field) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Object struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{2}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Object) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

var E_Schema = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Schema)(nil),
	Field:         88916,
	Name:          "graphql.schema",
	Tag:           "bytes,88916,opt,name=schema",
	Filename:      "graphql.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Field)(nil),
	Field:         88916,
	Name:          "graphql.field",
	Tag:           "bytes,88916,opt,name=field",
	Filename:      "graphql.proto",
}

var E_Object = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Object)(nil),
	Field:         88916,
	Name:          "graphql.object",
	Tag:           "bytes,88916,opt,name=object",
	Filename:      "graphql.proto",
}

func init() {
	proto.RegisterEnum("graphql.Scalar", Scalar_name, Scalar_value)
	proto.RegisterType((*Schema)(nil), "graphql.Schema")
	proto.RegisterType((*Field)(nil), "graphql.Field")
	proto.RegisterType((*Object)(nil), "graphql.Object")
	proto.RegisterExtension(E_Schema)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Object)
}

func init() { proto.RegisterFile("graphql.proto", fileDescriptor_3ce0fc368bdc1a51) }

var fileDescriptor_3ce0fc368bdc1a51 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x97, 0x36, 0xf1, 0xd2, 0x33, 0x31, 0x2c, 0x5f, 0xa0, 0x6a, 0x82, 0x51, 0xf5, 0x86,
	0x09, 0x69, 0xa9, 0xb4, 0x55, 0xbd, 0x28, 0x12, 0x12, 0x11, 0x1d, 0x14, 0x95, 0x45, 0x72, 0xbb,
	0x0b, 0xb8, 0x73, 0x52, 0x2f, 0x2d, 0x4a, 0xe3, 0x2c, 0x71, 0x84, 0xfa, 0x06, 0x3c, 0x11, 0x4f,
	0xc2, 0x03, 0x21, 0xff, 0x49, 0x81, 0x96, 0xdd, 0xf9, 0xfc, 0x4e, 0xce, 0xe7, 0xcf, 0xdf, 0x09,
	0x3c, 0x49, 0x4b, 0x56, 0xac, 0x1e, 0xb2, 0xa0, 0x28, 0x85, 0x14, 0xe4, 0xd8, 0x96, 0x67, 0xbd,
	0x54, 0x88, 0x34, 0xe3, 0x03, 0x8d, 0xe3, 0xfa, 0x7e, 0xb0, 0xe4, 0x55, 0x52, 0xae, 0x0b, 0x29,
	0x4a, 0xf3, 0x69, 0xff, 0x87, 0x03, 0x68, 0x9e, 0xac, 0xf8, 0x86, 0x91, 0x67, 0xe0, 0x3d, 0xd4,
	0xbc, 0xdc, 0x76, 0x9d, 0x9e, 0x73, 0xd1, 0xf9, 0x78, 0x44, 0x4d, 0x49, 0x9e, 0x83, 0xbf, 0xa9,
	0x25, 0x93, 0x6b, 0x91, 0x77, 0x5b, 0xb6, 0xb5, 0x23, 0xe4, 0x1c, 0x3a, 0x55, 0x1d, 0x2b, 0xd5,
	0x98, 0x77, 0xdb, 0xb6, 0xfd, 0x07, 0x91, 0x1e, 0x9c, 0x34, 0x97, 0x2a, 0x01, 0x57, 0x7d, 0x41,
	0xff, 0x46, 0x21, 0x02, 0x57, 0x6e, 0x0b, 0xde, 0xcf, 0xc1, 0xbb, 0x59, 0xf3, 0x6c, 0x49, 0x5e,
	0x01, 0xaa, 0x12, 0x96, 0xb1, 0x52, 0x3b, 0x39, 0xbd, 0x7a, 0x1a, 0x34, 0xcf, 0x9b, 0x6b, 0x4c,
	0x6d, 0x9b, 0x9c, 0x81, 0x9f, 0xd7, 0x59, 0xc6, 0xe2, 0x8c, 0x6b, 0x67, 0x3e, 0xdd, 0xd5, 0xfb,
	0xf7, 0xb6, 0x0f, 0xee, 0xed, 0xbf, 0x05, 0x14, 0xc5, 0xdf, 0x78, 0x22, 0x09, 0x01, 0x37, 0x67,
	0x1b, 0x6e, 0x1e, 0x4e, 0xf5, 0x79, 0x7f, 0xbe, 0x75, 0x30, 0xff, 0x3a, 0x57, 0xc9, 0x69, 0x1f,
	0x3e, 0xb8, 0x61, 0x14, 0xcd, 0xf0, 0x11, 0x01, 0x40, 0xf3, 0x05, 0x9d, 0xde, 0x7e, 0xc0, 0x0e,
	0xe9, 0x80, 0x37, 0xbd, 0x5d, 0x5c, 0x5f, 0xe1, 0x96, 0xc2, 0x77, 0xe6, 0xdc, 0xb6, 0x78, 0x34,
	0xc4, 0x6e, 0x83, 0x47, 0x43, 0xec, 0x29, 0x7c, 0x33, 0x8b, 0xde, 0x2d, 0x30, 0x52, 0xf8, 0x7d,
	0x74, 0x17, 0xce, 0x26, 0xf8, 0x58, 0xe1, 0xf0, 0xcb, 0x62, 0x32, 0xc7, 0xfe, 0x78, 0xaa, 0x62,
	0xd1, 0x9b, 0x3a, 0x0f, 0xcc, 0x5e, 0x83, 0x66, 0xaf, 0xc1, 0x67, 0x2e, 0x57, 0x62, 0x19, 0x69,
	0x63, 0x55, 0xf7, 0xd7, 0x4f, 0xaf, 0xe7, 0x5c, 0x9c, 0xfc, 0x13, 0x9c, 0x1a, 0xa4, 0x56, 0x60,
	0x3c, 0x01, 0xef, 0x5e, 0x47, 0xfd, 0xe2, 0x40, 0x49, 0xaf, 0x60, 0x5f, 0xe8, 0x74, 0x27, 0xa4,
	0xdb, 0xd4, 0x4c, 0x8f, 0x3f, 0x01, 0x12, 0x26, 0xc1, 0x97, 0xff, 0x71, 0x54, 0x55, 0x2c, 0xe5,
	0x8f, 0x5b, 0x32, 0xd9, 0x53, 0xab, 0x10, 0x8e, 0xbe, 0x0e, 0xd3, 0xb5, 0x5c, 0xd5, 0x71, 0x90,
	0x88, 0xcd, 0x20, 0x2d, 0x8b, 0xe4, 0x32, 0xa9, 0x2b, 0xa9, 0xcf, 0x7a, 0xe0, 0x32, 0x65, 0x92,
	0x7f, 0x67, 0x5b, 0xf3, 0x33, 0xbf, 0xb1, 0x34, 0x46, 0xba, 0xbc, 0xfe, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x5e, 0xbc, 0xfe, 0xbc, 0x03, 0x03, 0x00, 0x00,
}
