// Code generated by pkg/template/gen.go DO NOT EDIT.
package template

import (
	"text/template"
)

var handlerTemplate = template.Must(template.New("handler").
	Parse(`
{{ range $svc := .Services }}
func Register{{ $svc.GetName }}{{ $.RegisterFuncSuffix }}FromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
    conn, err := grpc.DialContext(ctx, endpoint, opts...)
    if err != nil {
        return
    }
    defer func() {
        if err != nil {
            if e := conn.Close(); e != nil {
                grpclog.Infof("Failed to close conn to %s: %v", endpoint, e)
            }
            return
        }
        go func() {
            <-ctx.Done()
            if e := conn.Close(); e != nil {
                grpclog.Infof("Failed to close conn to %s: %v", endpoint, e)
            }
        }()
    }()
    return Register{{ $svc.GetName }}{{ $.RegisterFuncSuffix }}Handler(mux, conn)
}

func Register{{ $svc.GetName }}{{ $.RegisterFuncSuffix }}Handler(mux *runtime.ServeMux, conn *grpc.ClientConn) error {
    return Register{{ $svc.GetName }}{{ $.RegisterFuncSuffix }}HandlerClient(mux, New{{ $svc.GetName }}Client(conn))
}

func Register{{ $svc.GetName }}{{ $.RegisterFuncSuffix }}HandlerClient(mux *runtime.ServeMux, client {{ $svc.GetName }}Client) error {
{{ range $method := $svc.Methods -}}
    {{ if $method.HasGraphQLMethod -}}
        // gRPC {{ $method.FullMethod }}
        {{ $method.Variable }} := &graphql.Field{
            Name: "{{ $method.FullMethod }}",
            Description: "{{ $method.Description }}",
            Type: {{ $method.Response.GetSchemaTypeName }},
            Args: graphql.FieldConfigArgument{
                {{ range $field := $method.Request.Fields -}}
                    "{{ $field.GetJsonName }}": &graphql.ArgumentConfig{
                        Type: {{ $field.ScalarType }},
                    },
                {{ end }}
            },
            Resolve: func(p graphql.ResolveParams) (interface{}, error) {
                in := &{{ $method.Request.GetGoTypeName }}{}
                {{ range $field := $method.Request.Fields -}}
                    {{ $field.Variable }}, ok := p.Args["{{ $field.GetJsonName }}"].({{ $field.GoType }})
                    if !ok {
                    {{ if $field.IsNullable -}}
                        {{ $field.Variable }} = {{ $field.GoDefaultValue }}
                    {{ else -}}
                        return nil, runtime.ErrInvalidArguments
                    {{ end -}}
                    }
                    in.{{ $field.FieldName }} = {{ $field.Variable }}
                {{ end -}}
                ctx := runtime.Context(p.Context)
                return client.{{ $method.GetName }}(ctx, in)
            },
        }
        {{ if $method.Query -}}
            mux.AddQuery("{{ $method.FieldName }}", {{ $method.Variable }})
        {{ else if $method.Mutation -}}
            mux.AddMutation("{{ $method.FieldName }}", {{ $method.Variable }})
        {{ else if $method.Subscribe -}}
            mux.AddSubscribe("{{ $method.FieldName }}", {{ $method.Variable }})
        {{ end -}}
    {{ end -}}
{{ end -}}
    return nil
}
{{ end -}}

`))
