// Code generated by pkg/template/gen.go DO NOT EDIT.
package template

import (
    "text/template"
)

var schemasTemplate = template.Must(template.New("schemas").
Parse(`
var (
{{ range $msg := .Messages }}
    {{ $msg.GetSchemaTypeName }} = graphql.NewObject(graphql.ObjectConfig{
        Name: "{{ $msg.FieldName }}",
        Fields: graphql.Fields{
        {{ range $field := $msg.Fields -}}
            "{{ $field.GetJsonName }}": &graphql.Field{
                Type: {{ $field.ScalarType }},
            },
        {{ end }}
        },
    })
{{ end }}
)

`))
