// Code generated by pkg/template/gen.go DO NOT EDIT.
package template

import (
	"text/template"
)

var schemasTemplate = template.Must(template.New("schemas").
	Parse(`
var (
{{ range $msg := .Messages }}
    {{ $msg.GetSchemaTypeName }} = graphql.NewObject(graphql.ObjectConfig{
        Name: "{{ $msg.Name }}",
        Fields: graphql.Fields{
        {{ range $field := $msg.Fields -}}
            {{ if eq $field.Exclude false -}}
            "{{ $field.GetJsonName }}": &graphql.Field{
                Type: {{ $field.ScalarType }},
            },
            {{ end -}}
        {{ end }}
        },
    })
{{ end }}
)

func RegisterGQLObjectTypes(mux *runtime.ServeMux) {
{{- range $msg := .Messages }}
    {{- if $msg.IsObject }}
        mux.AddObjectType({{ $msg.GetSchemaTypeName }})
    {{- end }}
{{- end }}
}

`))
