// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-custom/graphql-gateway/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Gender int32

const (
	Gender_GENDER_UNKNOWN Gender = 0
	Gender_MALE           Gender = 1
	Gender_FEMALE         Gender = 2
)

var Gender_name = map[int32]string{
	0: "GENDER_UNKNOWN",
	1: "MALE",
	2: "FEMALE",
}

var Gender_value = map[string]int32{
	"GENDER_UNKNOWN": 0,
	"MALE":           1,
	"FEMALE":         2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Birthdate            int32                `protobuf:"varint,3,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Point                int64                `protobuf:"varint,4,opt,name=point,proto3" json:"point,omitempty"`
	Disabled             bool                 `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Gender               Gender               `protobuf:"varint,6,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetBirthdate() int32 {
	if m != nil {
		return m.Birthdate
	}
	return 0
}

func (m *User) GetPoint() int64 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *User) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *User) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_GENDER_UNKNOWN
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserRequest struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Birthdate            int32                `protobuf:"varint,2,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Point                int64                `protobuf:"varint,3,opt,name=point,proto3" json:"point,omitempty"`
	Disabled             bool                 `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Gender               Gender               `protobuf:"varint,5,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetBirthdate() int32 {
	if m != nil {
		return m.Birthdate
	}
	return 0
}

func (m *CreateUserRequest) GetPoint() int64 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *CreateUserRequest) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *CreateUserRequest) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_GENDER_UNKNOWN
}

func (m *CreateUserRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterEnum("user.Gender", Gender_name, Gender_value)
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "user.GetUserResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xc1, 0x6e, 0xd3, 0x4c,
	0x14, 0x85, 0xff, 0x71, 0x1c, 0x27, 0xb9, 0xf9, 0x65, 0xca, 0xa8, 0x14, 0xcb, 0x54, 0x30, 0xb2,
	0x58, 0x58, 0x54, 0x75, 0x84, 0x61, 0xc3, 0x32, 0x02, 0x93, 0x05, 0x10, 0x24, 0x43, 0xc5, 0x32,
	0x1a, 0xdb, 0x17, 0xc7, 0x52, 0x1c, 0xbb, 0xf6, 0x18, 0xd4, 0x17, 0xe1, 0x01, 0xfa, 0x0e, 0x7d,
	0x01, 0xf6, 0xbc, 0x13, 0xf2, 0x8c, 0xdd, 0x56, 0xa9, 0x52, 0x76, 0x77, 0xce, 0x9c, 0x73, 0x3d,
	0xf7, 0x9b, 0x31, 0x40, 0x53, 0x63, 0xe5, 0x95, 0x55, 0x21, 0x0a, 0xaa, 0xb7, 0xb5, 0xfd, 0x2c,
	0x2d, 0x8a, 0x74, 0x83, 0x33, 0xa9, 0x45, 0xcd, 0xf7, 0x99, 0xc8, 0x72, 0xac, 0x05, 0xcf, 0x4b,
	0x65, 0xb3, 0x9f, 0xec, 0x1a, 0x30, 0x2f, 0xc5, 0x45, 0xb7, 0xf9, 0x3a, 0xcd, 0xc4, 0xba, 0x89,
	0xbc, 0xb8, 0xc8, 0x67, 0x69, 0x55, 0xc6, 0xa7, 0x71, 0x53, 0x0b, 0x59, 0xf3, 0x72, 0x7d, 0xbe,
	0x39, 0x4d, 0xb9, 0xc0, 0x9f, 0xfc, 0xa2, 0x5f, 0xab, 0x94, 0xf3, 0x4b, 0x03, 0xfd, 0xac, 0xc6,
	0x8a, 0x9a, 0xa0, 0x65, 0x89, 0x45, 0x18, 0x71, 0x27, 0xa1, 0x96, 0x25, 0x94, 0x82, 0xbe, 0xe5,
	0x39, 0x5a, 0x9a, 0x54, 0x64, 0x4d, 0x8f, 0x61, 0x12, 0x65, 0x95, 0x58, 0x27, 0x5c, 0xa0, 0x35,
	0x60, 0xc4, 0x1d, 0x86, 0x37, 0x02, 0x3d, 0x84, 0x61, 0x59, 0x64, 0x5b, 0x61, 0xe9, 0x8c, 0xb8,
	0x83, 0x50, 0x2d, 0xa8, 0x0d, 0xe3, 0x24, 0xab, 0x79, 0xb4, 0xc1, 0xc4, 0x1a, 0x32, 0xe2, 0x8e,
	0xc3, 0xeb, 0x35, 0x7d, 0x0e, 0x46, 0x8a, 0xdb, 0x04, 0x2b, 0xcb, 0x60, 0xc4, 0x35, 0xfd, 0xff,
	0x3d, 0xc9, 0x64, 0x21, 0xb5, 0xb0, 0xdb, 0xa3, 0x6f, 0x00, 0xe2, 0x0a, 0xb9, 0xc0, 0x64, 0xc5,
	0x85, 0x35, 0x62, 0xc4, 0x9d, 0xfa, 0xb6, 0xa7, 0x50, 0x78, 0x3d, 0x0a, 0xef, 0x6b, 0xcf, 0x2a,
	0x9c, 0x74, 0xee, 0xb9, 0x68, 0xa3, 0x4d, 0x99, 0xf4, 0xd1, 0xf1, 0xbf, 0xa3, 0x9d, 0x7b, 0x2e,
	0x1c, 0x06, 0xe6, 0x02, 0x45, 0x8b, 0x26, 0xc4, 0xf3, 0x06, 0x6b, 0xb1, 0x4b, 0xc8, 0x79, 0x09,
	0x0f, 0xae, 0x1d, 0x75, 0x59, 0x6c, 0x6b, 0xa4, 0x4f, 0x41, 0xde, 0xa4, 0x34, 0x4d, 0x7d, 0x50,
	0xe3, 0x48, 0x87, 0xd4, 0x9d, 0x3f, 0x04, 0x1e, 0xbe, 0x95, 0xa7, 0xbb, 0xdd, 0xb8, 0x47, 0x4d,
	0xf6, 0xa1, 0xd6, 0xf6, 0xa2, 0x1e, 0xec, 0x43, 0xad, 0xef, 0x45, 0x3d, 0xbc, 0x07, 0xb5, 0x07,
	0x7a, 0xfb, 0xe6, 0xe4, 0x75, 0xdc, 0x4f, 0x4a, 0xfa, 0x5e, 0xf8, 0x60, 0xa8, 0x0e, 0x94, 0x82,
	0xb9, 0x08, 0x96, 0xef, 0x82, 0x70, 0x75, 0xb6, 0xfc, 0xb0, 0xfc, 0xfc, 0x6d, 0x79, 0xf0, 0x1f,
	0x1d, 0x83, 0xfe, 0x69, 0xfe, 0x31, 0x38, 0x20, 0x14, 0xc0, 0x78, 0x1f, 0xc8, 0x5a, 0xf3, 0x7f,
	0x13, 0x98, 0xb6, 0xd3, 0x7f, 0xc1, 0xea, 0x47, 0x16, 0x23, 0x0d, 0x61, 0xd4, 0x61, 0xa4, 0x87,
	0xfd, 0xa1, 0x6e, 0x73, 0xb7, 0x1f, 0xed, 0xa8, 0x8a, 0xb5, 0x63, 0x5f, 0x5e, 0x9d, 0x1c, 0xc1,
	0x28, 0x55, 0xb2, 0x33, 0x4d, 0x51, 0xd4, 0x8c, 0xb3, 0xd6, 0x4b, 0x57, 0x00, 0x37, 0x98, 0xe9,
	0x63, 0xd5, 0xe0, 0x0e, 0x78, 0xfb, 0xe8, 0xce, 0x80, 0x41, 0xfb, 0x43, 0x39, 0xec, 0xf2, 0xea,
	0xe4, 0x98, 0x76, 0xaf, 0x4e, 0x76, 0x37, 0x55, 0xdd, 0x7f, 0x20, 0x32, 0x64, 0xe2, 0xd5, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x50, 0xdd, 0xd7, 0xc5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*empty.Empty, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
